Wip #990 promotion rule by guest occupation
channainfo/commissioner pull request #1000
Opened 2024-01-09 10:33 UTC by panhachom

2024-01-11 07:51 UTC, theachoem commented on app/models/spree_cm_commissioner/promotion/rules/guest_occupations.rb
> +        def actionable?(line_item)
actionable if it line_item is eligible, let reuse logic in `eligible?` method.

2024-01-11 07:55 UTC, theachoem requested changes

2024-01-11 07:55 UTC, theachoem commented on app/models/spree_cm_commissioner/promotion/rules/guest_occupations.rb
> +          line_item.guests.any? { |guest| guest.occupation_id == occupation_id }
this method is not used, shouldn't keep to avoid confusion. Or we can move it to line_item_decorator.

2024-01-15 02:24 UTC, theachoem commented on app/models/spree_cm_commissioner/promotion/rules/guest_occupations.rb
> +        def match_policy_condition(line_item)
match_policy_condition?

2024-01-15 04:30 UTC, channainfo requested changes

2024-01-15 04:30 UTC, channainfo commented on app/models/spree_cm_commissioner/guest_occupation_promotion_rule.rb
> +    belongs_to :taxon, class_name: 'Spree::Taxon'
let's rename it from taxon to occupation to make it clear.

2024-01-15 13:04 UTC, merged