close #1011 change transit taxonomies url
channainfo/commissioner pull request #1015
Opened 2024-01-15 07:33 UTC by tykeaboyloy

2024-01-15 13:06 UTC, channainfo commented
@tykeaboyloy conflict

2024-01-16 04:51 UTC, channainfo requested changes

2024-01-16 04:51 UTC, channainfo commented on app/controllers/spree/transit/places_controller.rb
> +        @places_taxonomy = Spree::Taxonomy.find_by(name: 'Places', kind: 'transit')
Let's just use the kind:. Name is subjected to change based on the translation.

2024-01-22 04:03 UTC, chheng-dev commented on app/controllers/spree/transit/places_controller.rb
> +          Spree::Taxonomy.create(name: 'Places', kind: 'transit', store: current_store)
Fixed bong

2024-02-12 02:49 UTC, merged