WIP #1038 decorate set quantity from cart controller
channainfo/commissioner pull request #1039
Opened 2024-01-22 02:39 UTC by vaneath

Issue #1038

2024-01-23 17:56 UTC, theachoem commented on app/services/spree_cm_commissioner/cart/recalculate.rb
> +        order_updater = ::Spree::OrderUpdater.new(order)
remove this

2024-01-24 02:02 UTC, channainfo requested changes

2024-01-24 02:02 UTC, channainfo commented on app/controllers/spree_cm_commissioner/api/v2/storefront/cart_controller_decorator.rb
> +          def set_quantity
we don't use the set_* for action.  Try to avoid custom actions.

2024-01-24 02:02 UTC, channainfo commented on spec/services/spree_cm_commissioner/cart/set_quantity_spec.rb
> +  context "it removes guests and set quantity" do
context is used for a conditional statement, for example, with... or when...

2024-01-25 16:37 UTC, vaneath commented
Changed flow to delete guest. PR #1048

2024-01-25 16:37 UTC, closed without merging