WIP #1031 get api for check_in dashboard
channainfo/commissioner pull request #1041
Opened 2024-01-23 10:20 UTC by LengTech11

2024-01-25 08:39 UTC, theachoem commented on app/interactors/spree_cm_commissioner/operator_dashboard_interactor.rb
> +    end
```rb
def call
   dashboard_query_result = dashboard_query

    context.pie_charts = result.group_by { |row| row['chart_type'] }.map do |chart_type, rows|
        create_pie_chart_for(chart_type: chart_type, rows: rows)
     end
end

def dashboard_query
   OperatorDashboardDataQuery.call
end
```

```rb
allow_any_instance_of(OperatorDashboardInteractor).to_recieve(:dashboard_query).and_return([
  {'chart_type': 'gender', pies: []}, {'chart_type': 'gender', pies: []}, 
])

context = OperatorDashboardDataQuery.call
expect(context.pie_charts[0].chart_type).to eq 'gender'
```

2024-01-25 10:51 UTC, channainfo requested changes

2024-01-25 10:51 UTC, channainfo commented on app/controllers/spree/api/v2/operator/operator_pie_charts_controller.rb
> +            render_serialized_payload(201) do
Use 200 status code

2024-01-25 10:51 UTC, channainfo commented on app/interactors/spree_cm_commissioner/operator_pie_chart_interactor.rb
> +    def self.call
Use def call instead.

2024-01-25 10:51 UTC, channainfo commented on app/controllers/spree/api/v2/operator/operator_pie_charts_controller.rb
> +            objects = SpreeCmCommissioner::OperatorPieChartInteractor.call
This method should receive an event , a date and a chart type( gender, profession,...)

2024-01-25 10:51 UTC, channainfo commented on app/queries/spree_cm_commissioner/operator_pie_chart_data_queries.rb
> +      "SELECT list_all_guest.*, check_in_data.guest_id AS has_check_ins,
Use the heredoc syntax for multi line strings

2024-01-25 10:51 UTC, channainfo commented on app/queries/spree_cm_commissioner/operator_pie_chart_data_queries.rb
> +      "SELECT genders.genders, COUNT(*) as pie
Find a way to reuse this code by passing a type in.

2024-01-30 03:54 UTC, channainfo requested changes

2024-01-30 03:54 UTC, channainfo commented on app/queries/spree_cm_commissioner/operator_pie_chart_data_queries.rb
> +    def self.operator_pie_charts_queries
let's not calculate all in a single method. we should have to pass in a chart type for example a chart for the gender. we return only that specific chart. The app needs to send to the API with a corresponding chart type.

2024-01-31 02:41 UTC, channainfo requested changes

2024-01-31 02:41 UTC, channainfo commented on app/interactors/spree_cm_commissioner/operator_pie_chart_interactor.rb
> +
```
# chart_type: gender | entry_type | 
 def create_pie_chart_for(chart_type:, rows:)
```

2024-01-31 02:41 UTC, channainfo commented on app/interactors/spree_cm_commissioner/operator_pie_chart_interactor.rb
> +
```
Rails.cache.fetch("#{chart_type}-#{event_id}", expires_in: 30.minutes) do
   create_pie_chart_for(chart_type: ...)
end

```

2024-02-13 14:04 UTC, merged