Close #1050 create a product tab and then connect the product to the taxon
channainfo/commissioner pull request #1053
Opened 2024-01-26 17:24 UTC by Sreyleak-Deth

2024-01-27 00:15 UTC, channainfo requested changes

2024-01-27 00:15 UTC, channainfo commented on app/views/spree/admin/classifications/index.html.erb
> +  <div class="table-responsive border rounded bg-white mb-3">
Let's reuse the product partial

2024-01-27 07:02 UTC, Sreyleak-Deth commented
Noted bong, I will correct

On Sat, Jan 27, 2024, 7:15 AM Channa Ly ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In app/views/spree/admin/classifications/index.html.erb
> <https://github.com/channainfo/commissioner/pull/1053#discussion_r1468254081>
> :
>
> > +  <%= link_to Spree.t(:taxonomies), spree.admin_taxonomies_url %> /
> +
> +  <%= link_to @taxonomy.root.name, ***@***.***) %>
> +  <% unless @taxon.root? %>
> +   / <%= @taxon.name %>
> +   <% end %>
> +<% end %>
> +
> +<% content_for :page_actions do %>
> +  <%= button_link_to Spree.t(:add_new_product), new_admin_taxonomy_taxon_classification_path, class: "btn-success", icon: 'add.svg', id: 'admin_new_vendor_link' %>
> +<% end if can? :create,  Spree::Classification %>
> +
> +<%= render partial: 'spree/admin/shared/taxon_tabs', locals: { current: :products } %>
> +
> +<% if @taxon_products.any? %>
> +  <div class="table-responsive border rounded bg-white mb-3">
>
> Let's reuse the product partial
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/channainfo/commissioner/pull/1053#pullrequestreview-1846751912>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3UEJP22JUO7HZZQDMFL6STYQRBLFAVCNFSM6AAAAABCMPE6KKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBWG42TCOJRGI>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2024-01-30 11:23 UTC, Sreyleak-Deth commented
For the product here, it just shows the data of the product that has a relationship with the taxon. And I checked it again, and again, it doesn't have the view of taxon_product; it just has the view of product only. This shows I can't use a partial to render the product list or a product row. What I do here is just show the product_id and product_name that have a connection with the taxon only.

2024-02-01 12:20 UTC, channainfo requested changes

2024-02-01 12:20 UTC, channainfo commented on app/views/spree/admin/classifications/shared/_products.html.erb
> +
Put this file in the app/views/spree/admin/shared/_products.html.erb instead.

2024-02-02 03:45 UTC, merged