Close #1079 add sub title column and add sub title in taxon page
channainfo/commissioner pull request #1081
Opened 2024-02-02 11:00 UTC by Sreyleak-Deth

2024-02-02 16:20 UTC, theachoem requested changes
Let rename to subtitle instead

2024-02-02 16:35 UTC, Sreyleak-Deth commented
> Let rename to subtitle instead

which part b, i can't fund the file that you want me to rename

2024-02-03 00:51 UTC, channainfo requested changes

2024-02-03 00:51 UTC, channainfo commented on app/overrides/spree/admin/taxons/_form/sub_title.html.erb.deface
> +    <%= text_field :taxon, :sub_title, class: 'form-control', required: true %>
Use f.text_field instead. Check the main form to see how to use the text field

2024-02-03 03:41 UTC, Sreyleak-Deth commented on app/overrides/spree/admin/taxons/_form/sub_title.html.erb.deface
> +    <%= text_field :taxon, :sub_title, class: 'form-control', required: true %>
> Use f.text_field instead. Check the main form to see how to use the text field

Noted bong, I will correct it

2024-02-03 04:00 UTC, Sreyleak-Deth commented on app/overrides/spree/admin/taxons/_form/sub_title.html.erb.deface
> +    <%= text_field :taxon, :sub_title, class: 'form-control', required: true %>
> Use f.text_field instead. Check the main form to see how to use the text field

resolved bong

2024-02-04 11:39 UTC, theachoem requested changes

2024-02-04 11:39 UTC, theachoem commented on app/overrides/spree/admin/taxons/_form/sub_title.html.erb.deface
> +  <%= f.field_container :sub_title do %>
let rename to subtitle

2024-02-04 11:39 UTC, theachoem commented on app/serializers/spree/v2/storefront/taxon_serializer_decorator.rb
> +          base.attributes :custom_redirect_url, :kind, :sub_title
rename subtitle as well.

2024-02-04 11:39 UTC, theachoem commented on config/initializers/spree_permitted_attributes.rb
> +      sub_title
rename

2024-02-04 11:39 UTC, theachoem commented on db/migrate/20240202101246_add_sub_title_to_spree_taxon.rb
> +    add_column :spree_taxons, :sub_title, :string, if_not_exists: true
rename

2024-02-04 11:39 UTC, theachoem commented on spec/serializers/spree/v2/storefront/taxon_serializer_spec.rb
> +        :sub_title,
rename to subtitle

2024-02-05 05:24 UTC, merged