close #1084 add update button to update the updated_at field for homepage section
channainfo/commissioner pull request #1085
Opened 2024-02-05 04:39 UTC by vaneath

2024-02-12 02:56 UTC, channainfo requested changes

2024-02-12 02:56 UTC, channainfo commented on app/controllers/spree/admin/homepage_section_controller.rb
> +      def update_the_updated_at
why we need this?

2024-02-13 14:41 UTC, vaneath commented on app/controllers/spree/admin/homepage_section_controller.rb
> +      def update_the_updated_at
Bong thea said sections are cached once it's loaded, and only clear after the updated_at field is updated. This button will update the updated_at to Time.zone.now so operator can manually update all sections to latest setup, without any glitch of cache.

2024-02-14 02:15 UTC, channainfo commented on app/controllers/spree/admin/homepage_section_controller.rb
> +      def update_the_updated_at
Let's explicitly clear the cache instead. Create an item under the Settings called "Caches" which lists all the cache along with actions to clear the cache. In the meantime, we just need to list down the most important caches to be cleared.

2024-03-18 10:53 UTC, vaneath commented
close as not currently needed.

2024-03-18 10:53 UTC, closed without merging