close #1097 add section_type column to homepage_section table
channainfo/commissioner pull request #1098
Opened 2024-02-07 08:53 UTC by vaneath

![Screenshot from 2024-02-07 15-52-41](https://github.com/channainfo/commissioner/assets/109834020/6175c5eb-a0eb-4b11-aafa-076a136ae11a)

2024-02-12 03:47 UTC, channainfo requested changes

2024-02-12 03:47 UTC, channainfo commented on app/models/spree_cm_commissioner/homepage_section.rb
> +    enum section_type: {
Let's call it "segment" instead store it as an integer and use it as a bitwise instead of the enum.

2024-02-12 03:47 UTC, channainfo commented on app/views/spree/admin/homepage_section/_form.html.erb
> +            <%= f.select :section_type, SpreeCmCommissioner::HomepageSection.section_types.keys, {}, { class: 'fullwidth select2' } %>
use a checkbox and allow user to enter different at least of the the values

2024-02-12 06:41 UTC, vaneath commented on app/views/spree/admin/homepage_section/_form.html.erb
> +            <%= f.select :section_type, SpreeCmCommissioner::HomepageSection.section_types.keys, {}, { class: 'fullwidth select2' } %>
noted b, my current flow using select type so that each section knows which homepage it belongs to, but if using bitwise and checkbox can be more flexible since each section may belong to more than 1 homepage. I will check that!

2024-02-13 02:42 UTC, channainfo commented on app/views/spree/admin/homepage_section/_form.html.erb
> +            <%= f.select :section_type, SpreeCmCommissioner::HomepageSection.section_types.keys, {}, { class: 'fullwidth select2' } %>
The **segment** and **section** are interchangeable. The term "type" tends to have a string value instead of a numeric value, thus we drop the **type** out. Segment tends to have more tendency toward a numeric value.

2024-02-15 03:00 UTC, vaneath commented
Moved to #1110

2024-02-15 03:00 UTC, closed without merging