close #1118 add new homepage background api
channainfo/commissioner pull request #1126
Opened 2024-02-16 03:45 UTC by vaneath

2024-02-16 08:33 UTC, channainfo commented
Resolve conflicts

2024-02-19 02:33 UTC, channainfo requested changes

2024-02-19 02:33 UTC, channainfo commented on app/controllers/spree/admin/homepage_section_controller.rb
> +      helper_method :badge_class_for_segment
remove this ```helper_method```. If you include the helper module, all its methods will be available to the controller and the view.

2024-02-19 02:59 UTC, vaneath commented on app/controllers/spree/admin/homepage_section_controller.rb
> +      helper_method :badge_class_for_segment
Helper module not working with include, now I change to helper instead of instead since it's a helper module. It should work not bong!

2024-02-19 09:32 UTC, vaneath commented on app/controllers/spree/admin/homepage_section_controller.rb
> +      helper_method :badge_class_for_segment
I use badge_class_for_segment for view and now I move calculate_segment_value to controller now it should work fine bong.

2024-02-19 10:14 UTC, vaneath commented on app/controllers/spree/admin/homepage_section_controller.rb
> +      helper_method :badge_class_for_segment
what is the best practice bong since:
include SpreeCmCommissioner::Admin::HomepageSegmentHelper will only available in controller scope. In order to use it in view I have to: helper SpreeCmCommissioner::Admin::HomepageSegmentHelper instead of include or define it like this:       helper_method :badge_class_for_segment.

2024-02-19 10:21 UTC, vaneath commented on app/controllers/spree/admin/homepage_section_controller.rb
> +      helper_method :badge_class_for_segment
I read from this bong: https://stackoverflow.com/questions/5130150/rails-how-to-use-a-helper-inside-a-controller

2024-02-19 10:34 UTC, channainfo commented on app/controllers/spree/admin/homepage_section_controller.rb
> +      helper_method :badge_class_for_segment
If you name your helper after your controller name, the methods will be available on both controller and the view. For the  Admin::HomepageSectionController the helper would be Admin::HomepageSectionHelper.

2024-02-19 10:35 UTC, merged