WIP #1148 add dashboard for organizer to view all guests informatio
channainfo/commissioner pull request #1149
Opened 2024-02-21 02:26 UTC by vaneath

2024-02-26 07:09 UTC, theachoem commented on app/models/spree_cm_commissioner/check_in_ability.rb
> +        can :manage, Guest
can manage both

2024-02-27 05:45 UTC, channainfo requested changes

2024-02-27 05:45 UTC, channainfo commented on spec/interactors/spree_cm_commissioner/check_in_bulk_creator_spec.rb
> +      p context.check_ins[1].entry_type
Remove this

2024-02-27 06:07 UTC, vaneath commented on spec/interactors/spree_cm_commissioner/check_in_bulk_creator_spec.rb
> +      p context.check_ins[1].entry_type
Done bong!

2024-02-27 06:24 UTC, merged