WIP #1195 export guest data to csv
channainfo/commissioner pull request #1196
Opened 2024-03-11 03:36 UTC by vaneath

2024-03-11 10:30 UTC, channainfo requested changes

2024-03-12 10:38 UTC, channainfo requested changes

2024-03-12 10:38 UTC, channainfo commented on app/interactors/spree_cm_commissioner/generate_csv.rb
> +      csv_data = CSV.generate(headers: true) do |csv|
we prefer generate the csv file here. Once it is done, return the file to be sent to the client in the controller.

2024-03-12 10:38 UTC, channainfo commented on app/controllers/spree/events/guests_controller.rb
> +            ).result
Don't load this into memory. it will be costly. If there are many records we will face issues. Generate a CSV file in the GenerateCsv instead.

2024-03-12 12:28 UTC, channainfo requested changes

2024-03-12 12:28 UTC, channainfo commented on app/interactors/spree_cm_commissioner/generate_csv.rb
> +      context.result = csv_data
Open a csv to write data into a file instead of returning a csv data. https://ruby-doc.org/stdlib-2.4.6/libdoc/csv/rdoc/CSV.html#method-c-open

2024-03-15 04:20 UTC, channainfo requested changes

2024-03-15 04:20 UTC, channainfo commented on app/controllers/spree/events/guests_controller.rb
> +            file_name = "#{current_event.name.gsub(' ', '_')}_Guests_Data.csv"
construct the absolute file name here and use the lowercase file name and we need a meta-data to know when the file is downloaded.

```
private

def csv_name
   @csv_name ||= "guests-data-#{current_event.id}-#{Time.current.to_i}.csv
end

```
and then

```
file_name = Rails.root.join('tmp', csv_name)
...
send_file(file_name)

```
Check the x-send-file option and test it.

2024-03-15 04:20 UTC, channainfo commented on spec/interactors/spree_cm_commissioner/generate_guests_csv_spec.rb
> +    end
Merge this into one only -- expect the file to be created correctly and read the content of the file back with correct data.

2024-03-18 10:37 UTC, vaneath commented on app/controllers/spree/events/guests_controller.rb
> +            file_name = "#{current_event.name.gsub(' ', '_')}_Guests_Data.csv"
I'm not so sure how to implement it  bong, these are the resources that I'm been researching recently. But it works fine right now.

References:
https://api.rubyonrails.org/v7.1.3/classes/ActionController/DataStreaming.html#method-i-send_file
https://github.com/heroku/heroku-buildpack-ruby/issues/783
https://gist.github.com/djo/11374407

2024-03-18 12:03 UTC, channainfo requested changes

2024-03-18 12:03 UTC, channainfo commented on app/controllers/spree/events/guests_controller.rb
> +            file_name = Rails.root.join('tmp', csv_name)
Move this out of the block

2024-03-19 04:39 UTC, merged