WIP #1241 export guest csv in background with sidekiq
channainfo/commissioner pull request #1247
Opened 2024-03-22 09:23 UTC by vaneath

2024-04-03 03:29 UTC, theachoem commented on app/interactors/spree_cm_commissioner/download_guest_csv.rb
> +        context.message = Spree.t('csv.csv_queued')
no need.

2024-04-04 10:29 UTC, vaneath commented
Latest Demo:

[Screencast from 2024-04-04 17-26-31.webm](https://github.com/channainfo/commissioner/assets/109834020/354bdcf6-9162-46c8-9ced-a794e77a4cbb)

2024-04-11 02:34 UTC, channainfo commented
Handle failed job / crash: https://stackoverflow.com/questions/29085458/how-to-access-perform-parameters-in-activejob-rescue

2024-04-11 02:53 UTC, channainfo requested changes

2024-04-11 02:53 UTC, channainfo commented on app/controllers/spree/events/data_exports_controller.rb
> +        when 'queue'
if you wanna handle this, move it to rescue_from Active Record  not found block instead.

2024-04-11 02:53 UTC, channainfo commented on app/controllers/spree/events/data_exports_controller.rb
> +          send_file(export_file.file_path, type: 'text/csv', filename: export_file.file_name)
use a presigned url with an expiration time set to 1.hour

2024-04-11 02:53 UTC, channainfo commented on app/controllers/spree/events/guests_controller.rb
> -      private
if it is a controller action add a comment with

```
# {HTTP_VERB}: /{route_full_path}
```

for example:

```
# POST /generate_guest_csv

```

2024-04-11 02:53 UTC, channainfo commented on app/models/spree_cm_commissioner/exports/export_guest_csv.rb
> +        @csv_name = "CM#{Time.current.to_i}"
use a more meaningful name, for instance, export-guest-csv or guest-csv

2024-04-11 02:53 UTC, channainfo commented on app/models/spree_cm_commissioner/exports/export_guest_csv.rb
> +      before_create :set_file_name, :set_file_path, :set_name, :set_export_type
Remove this line. it introduces complexity and readability

2024-04-11 02:53 UTC, channainfo commented on app/services/exports/export_guest_csv_service.rb
> +      sleep 20
remove this.

2024-04-11 02:53 UTC, channainfo commented on app/services/exports/export_guest_csv_service.rb
> +      export = SpreeCmCommissioner::Exports::ExportGuestCsv.find(id)
move this to memoized method instead
```
def export
   @export ||= SpreeCmCommissioner::Exports::ExportGuestCsv.find(id)
end

```

2024-04-11 02:53 UTC, channainfo commented on app/services/exports/export_guest_csv_service.rb
> +      export.update(status: :progress)
create another column called started_at and then set the value wen the job is in progress.

2024-04-11 02:53 UTC, channainfo commented on config/routes.rb
> +        post :download
make sure to add the comment in the controller action
```
# POST: /data_exports/download
```

for every custom controller action, you must add the comment to annotate the http verb and route path

2024-04-29 02:10 UTC, channainfo requested changes

2024-04-29 02:10 UTC, channainfo commented on app/models/spree_cm_commissioner/exports/export_guest_csv.rb
> +        set_name
remove all the set_ method. Doing this will cause use to do unnecesary test and lower down our test coverage for no reason. use @attributes = attributes instead.

2024-04-29 02:10 UTC, channainfo commented on db/migrate/20240327082849_create_spree_cm_commissioner_exports.rb
> +      t.string :uuid
set default length for uuid and add index to it. cm_exports should be a polymorphic as well.

2024-04-29 02:10 UTC, channainfo commented on spec/services/spree_cm_commissioner/exports/export_guest_csv_service_spec.rb
> +      end
add another spec to make sure that the file is created and the content is correctly generated.

2024-05-07 05:00 UTC, channainfo requested changes

2024-05-07 05:00 UTC, channainfo commented on app/controllers/spree/events/data_exports_controller.rb
> +        raise StandardError, 'Export file is not attached or export is not done' unless export.exported_file.attached? && export.done?
raise ActiveRecord::RecordNotFound instead.

2024-05-07 05:00 UTC, channainfo commented on app/controllers/spree/events/data_exports_controller.rb
> +      rescue_from StandardError do |exception|
don't rescue inline. use rescue_from AAA, with: :method_name instead.

2024-05-07 11:02 UTC, merged