close #1313 setup pricing model/rate model migrations
channainfo/commissioner pull request #1320
Opened 2024-04-08 05:01 UTC by theachoem

2024-04-10 12:42 UTC, theachoem commented on app/models/spree_cm_commissioner/price_decorator.rb
I changed from:

```rb
options = price_options.merge(tax_category: variant.tax_category)
```

```rb
options = price_options.merge(tax_category: tax_category)
```

2024-04-18 03:34 UTC, channainfo requested changes

2024-04-18 03:34 UTC, channainfo commented on app/models/concerns/spree_cm_commissioner/pricing_concern.rb
> +# :match_policy, :effective_from, :effective_to, :priority
if so, it would be better to remove the concern in favor of a plain ruby module instead.
I would call this module Ruleable or RuleablePrice instead.

2024-04-18 03:34 UTC, channainfo commented on app/models/spree_cm_commissioner/pricing_model.rb
> +    belongs_to :modelable, optional: false, polymorphic: true, inverse_of: :pricing_models, touch: true
This name might be taken by other gems. how about changing it to modelable_price instead?

2024-04-18 03:34 UTC, channainfo commented on app/models/concerns/spree_cm_commissioner/line_item_pricings_concern.rb
> +
add also has_many pricing_models / pricing_rates through applied_pricing_models / applied_pricing_rates

2024-04-18 03:34 UTC, channainfo commented on app/models/concerns/spree_cm_commissioner/priceable_concern.rb
> +      find_or_build_price(currency)
let's check this work around

2024-04-25 04:00 UTC, theachoem commented on app/models/concerns/spree_cm_commissioner/pricing_concern.rb
> +# :match_policy, :effective_from, :effective_to, :priority
https://api.rubyonrails.org/v7.1.3.2/classes/ActiveSupport/Concern.html.

concern look cleaner bong.

2024-04-25 07:23 UTC, theachoem commented on app/models/spree_cm_commissioner/pricing_model.rb
> +    belongs_to :modelable, optional: false, polymorphic: true, inverse_of: :pricing_models, touch: true
fixed!

2024-04-25 07:23 UTC, theachoem commented on app/models/concerns/spree_cm_commissioner/line_item_pricings_concern.rb
> +
fixed!

2024-04-25 07:55 UTC, theachoem commented on app/models/concerns/spree_cm_commissioner/priceable_concern.rb
> +      find_or_build_price(currency)
Error happens because of cache & loaded prices.

```rb
def price_in(currency)
  Rails.cache.fetch(cache_key) do
    find_or_build_price(currency)
  end
end

def find_or_build_price(currency)
  if prices.loaded?
    prices.detect { |price| price.currency == currency }
  else
    prices.find_or_initialize_by(currency: currency)
  end
end
```

When prices is loaded, we find price via prices.detect. I assume that loaded price are loaded to be singleton. That why when try to cache it, it raised `singleton can't be dumped` which mean we can't cache singleton class.

To fix it, we can just change find_or_build_price method to like following:
```rb
def price_in(currency)
  Rails.cache.fetch(cache_key) do
    find_or_build_price(currency)
  end
end

def find_or_build_price(currency)
   prices.find_or_initialize_by(currency: currency)
end
```

2024-04-29 14:05 UTC, merged