close #1326 add line item pricing computer
channainfo/commissioner pull request #1332
Opened 2024-04-10 08:33 UTC by theachoem

## What in this PR?
1. Add line_item_pricing_calculator.rb
2. Add variant_pricing_models_computer.rb: use within `line_item_pricing_calculator.rb`
3. Add variant_pricing_rates_computer.rb: use within `line_item_pricing_calculator.rb`
4. Add sample rules (use for both rule/model):
  - custom_date.rb
  - early_bird.rb
  - extra_adults.rb
  - group_booking.rb
  - weekend.rb
5. Add sample pricing model actions 
  - calculate_adjustment.rb

## What next?
This PR is just adding the calculator. The calculator isn't used anywhere yet. In the next PR, we will consider where to put it to calculate/recalculate the pricing rate & model to fit following cases:
- recalculate if early bird expired
- recalculate quantity update
- recalculate when user add guest & occupant (guest rate)
- ...

2024-04-29 14:06 UTC, channainfo commented
@theachoem let's rebase this.

2024-04-30 07:29 UTC, theachoem commented
@channainfo fixed bong!

2024-05-20 02:26 UTC, channainfo requested changes

2024-05-20 03:26 UTC, theachoem commented on app/models/spree_cm_commissioner/pricing_actions/calculate_adjustment.rb
> +                       .new(options.rate_amount, options.rate_currency, options.total_quantity)
It's recommended by robocop bong

<img width="844" alt="image" src="https://github.com/channainfo/commissioner/assets/29684683/a7eb67c4-5e95-494b-816a-f538b52ef4fe">

Reference:
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/OpenStructUse

2024-06-06 01:36 UTC, merged