close #1338 add age, emergency_contact, product_name to organizer dashbaord
channainfo/commissioner pull request #1340
Opened 2024-04-23 06:39 UTC by vaneath

2024-04-26 03:44 UTC, channainfo requested changes

2024-04-26 03:44 UTC, channainfo commented on app/views/spree/events/guests/index.html.erb
> +            <%= guest.line_item.product.name %>
It's unnecessary to render the same product details for every single row in the table. You might consider extracting this information to a separate section to display product details, rather than repeating it in each table row. This approach will streamline the table's appearance and improve readability.

2024-04-26 03:44 UTC, channainfo commented on app/views/spree/events/guests/index.html.erb
>              <%= guest.other_occupation&.titleize || guest.occupation&.name %>
@vaneath eager load relevant models.

2024-04-29 07:55 UTC, vaneath commented
closed as not necessary needed!

2024-04-29 07:55 UTC, closed without merging