close #1342 add missing guest serializer
channainfo/commissioner pull request #1344
Opened 2024-04-23 08:05 UTC by vaneath

2024-04-25 04:55 UTC, theachoem requested changes
Add guest serializer rspec

2024-04-26 03:45 UTC, channainfo requested changes

2024-04-26 03:45 UTC, channainfo commented on app/serializers/spree_cm_commissioner/v2/storefront/guest_serializer.rb
>                     :age, :emergency_contact, :other_organization, :expectation
Add a spec for this as well

2024-05-06 23:10 UTC, vaneath commented
Moved to #1395

2024-05-06 23:10 UTC, closed without merging