close #1352 send_all_now to all customer_notifications
channainfo/commissioner pull request #1391
Opened 2024-05-06 08:58 UTC by LengTech11

2024-05-08 02:29 UTC, channainfo requested changes

2024-05-08 02:29 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +        context = { customer_notification: customer_notification, user_ids: nil }
let's add a new fiels call all: true. it is easy to make mistake with user_ids: nil to refer to all. we need a more explicit one ( all: true ) to send to all.

2024-05-08 02:29 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +          response = SpreeCmCommissioner::CustomerNotificationSender.call(context)
is this run in the background job?

2024-05-08 02:40 UTC, LengTech11 commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +          response = SpreeCmCommissioner::CustomerNotificationSender.call(context)
No bong. in directly deliver notification to user by call notification content by user_id and notification_id

<img width="692" alt="Screenshot 2024-05-08 at 9 39 30 in the morning" src="https://github.com/channainfo/commissioner/assets/119285234/b114dfec-02fd-4019-9c20-7e47d0729b64">

2024-05-08 02:57 UTC, LengTech11 commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +        context = { customer_notification: customer_notification, user_ids: nil }
can I resolve it as like this ?

<img width="820" alt="Screenshot 2024-05-08 at 9 56 59 in the morning" src="https://github.com/channainfo/commissioner/assets/119285234/01803d1a-2d5f-4b00-8be7-f639be622a04">

2024-05-09 07:19 UTC, LengTech11 commented
#### Problem
https://github.com/channainfo/commissioner/issues/1411

2024-05-09 07:32 UTC, channainfo requested changes

2024-05-09 07:32 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +          context = { customer_notification: customer_notification, user_ids: user_ids }
wheter it sends to all or not, we must send using the queue.

2024-05-09 08:40 UTC, merged