close #1372 change issued-date from created_at to start_date
channainfo/commissioner pull request #1392
Opened 2024-05-06 10:09 UTC by tykealy

The reason for the change is to show the service start_date so that when the order/invoice recurs, the date will be consistent.

2024-05-08 02:26 UTC, channainfo commented
@tykealy plz add the reason why we did this in the description to we can learn and wont repeat this in the future

2024-05-09 06:52 UTC, Regene27 commented
The reason for the change is to show the service start_date so that when the order/invoice recurs, the date will be consistent.

2024-05-10 02:41 UTC, channainfo commented
> The reason for the change is to show the service start_date so that when the order/invoice recurs, the date will be consistent.

Put in the description of the issue as I mentioned above.

2024-05-14 05:42 UTC, channainfo requested changes

2024-05-14 05:42 UTC, channainfo commented on app/views/spree/billing/report/balance_due.html.erb
> +            <td><%= order.line_items[0].from_date.to_date %></td>
make sure you include line_items in the like this .includes(:line_items) to avoid n+1 query

2024-05-14 05:42 UTC, channainfo commented on app/views/spree/billing/report/paid.html.erb
> +            <td><%= order.line_items[0].from_date.to_date %></td>
make sure you include line_items in the like this .includes(:line_items) to avoid n+1 query

2024-05-14 05:42 UTC, channainfo commented on app/views/spree/billing/report/show.html.erb
> +            <td><%= order.line_items[0].from_date.to_date %></td>
make sure you include line_items in the like this .includes(:line_items) to avoid n+1 query

2024-05-20 02:10 UTC, merged