WIP #1423 push notification to user by taxon
channainfo/commissioner pull request #1436
Opened 2024-05-24 02:38 UTC by LengTech11

2024-05-27 10:23 UTC, channainfo requested changes

2024-05-27 10:23 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +          @notification_users[notification.id] = if notification.notification_taxons.present?
Don't load users here. This is a resource-extensive process and the memory might not fit well.  
Create another controller and use Ajax to fetch users from a specific notification instead.

2024-05-29 08:13 UTC, LengTech11 commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +          @notification_users[notification.id] = if notification.notification_taxons.present?
i create a new action for this and use AJAX in index view

2024-05-29 13:10 UTC, channainfo requested changes

2024-05-29 13:11 UTC, channainfo requested changes

2024-05-29 13:11 UTC, channainfo commented on app/views/spree/admin/customer_notifications/index.html.erb
> +    url: '/admin/customer_notifications/' + notificationId + '/fetch_users',
use another controller instead.

2024-05-29 15:14 UTC, LengTech11 commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +          if customer_notification.notification_taxons.present?
i split this to determin_user_ids , handle_send_all and handle_send_specific

2024-05-30 00:08 UTC, channainfo requested changes

2024-05-30 00:08 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +        Spree::User.joins(orders: { line_items: :variant })
extract this to a class and reuse it.

2024-05-30 00:08 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +          user_ids = users(customer_notification.notification_taxons.pluck(:taxon_id)).pluck(:id)
you should not do this. If the amount of users is huge it will degrade the app performance. If need this send it to queue job instead.

2024-05-30 00:08 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
>        def notification_sender
is this one an action or a method? If a custom action add a comment. we try to avoid custom actions as much as possible.

2024-05-30 00:08 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +        @notification_users = {} # Initialize as an empty hash
Remove this.

2024-05-30 01:53 UTC, LengTech11 commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +        Spree::User.joins(orders: { line_items: :variant })
i create a new class call it UsersByEventFetcherQuery

2024-05-30 02:26 UTC, LengTech11 commented on app/controllers/spree/admin/customer_notifications_controller.rb
> +          user_ids = users(customer_notification.notification_taxons.pluck(:taxon_id)).pluck(:id)
both handle_send_all and handle_send_specific methods are using a background job SpreeCmCommissioner::CustomerNotificationSenderJob to handle the process of sending notifications.

2024-05-30 02:44 UTC, channainfo requested changes

2024-05-30 02:46 UTC, channainfo requested changes

2024-05-30 02:46 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
>        def notification_sender
move to another controller.

2024-05-30 02:46 UTC, channainfo commented on app/controllers/spree/admin/customer_notifications_controller.rb
> -        if params[:send_all] == 'true'
move this a another class

2024-05-30 04:02 UTC, LengTech11 commented on app/controllers/spree/admin/customer_notifications_controller.rb
>        def notification_sender
i move this to new controller call NotificationSenderController and move logic to interactor call NotificationSendCreator

2024-05-30 07:08 UTC, merged