close #1460 add api for self check-in
channainfo/commissioner pull request #1467
Opened 2024-05-30 03:34 UTC by nenghakheng

2024-06-17 09:19 UTC, channainfo requested changes

2024-06-20 02:01 UTC, channainfo requested changes

2024-06-20 02:01 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/self_check_in_controller.rb
> +            unverified_decoded_jwt = JWT.decode(qr_data, nil, false)
Remove this: unverified_decoded_jwt. You can set leeway as a constant value and read it back when needed. use leeway 1minute.

2024-06-24 07:00 UTC, theachoem commented
@channainfo I merge to feature branch for now bong for refactoring.

2024-06-24 07:00 UTC, merged