close #1471 add video upload field to S3
channainfo/commissioner pull request #1515
Opened 2024-06-07 11:51 UTC by SreyMochOrng

2024-06-07 14:02 UTC, channainfo requested changes

2024-06-07 14:02 UTC, channainfo commented on app/models/spree_cm_commissioner/video_on_demand.rb
> +    has_one_attached :clip
let's rename from **clip** to **file**.

2024-06-07 14:50 UTC, SreyMochOrng commented on app/models/spree_cm_commissioner/video_on_demand.rb
> +    has_one_attached :clip
Done bong

2024-06-11 01:17 UTC, channainfo requested changes

2024-06-11 01:17 UTC, channainfo commented on app/overrides/spree/admin/shared/_product_tabs/video_on_demand.html.erb.deface
> +<% if @product.product_type == 'video' %>
Let's remove this condition all kinds of products can upload video.

2024-06-11 03:26 UTC, merged