Close #1533 create api promotion coupon code
channainfo/commissioner pull request #1534
Opened 2024-06-17 12:56 UTC by Sreyleak-Deth

### Add the code line below to store_decorator.rb because it undefined method 'default_notification_image' 
```
 base.has_one :default_notification_image, class_name: 'SpreeCmCommissioner::FeatureImage', dependent: :destroy, as: :viewable
 base.accepts_nested_attributes_for :default_notification_image, reject_if: :all_blank
 
```

### BaseUrl:  
```
{{BASE_URL}}/api/v2/storefront/user_promotion?include=default_store

```
```json
{
    "data": [
        {
            "id": "121",
            "type": "promotion",
            "attributes": {
                "name": "20% off for New Users",
                "description": "spen 4$,  valid for a minimun order of $5, Expiration: Promotion subject to change or termination.",
                "code": "ADFFD+",
                "expires_at": "2024-06-28T12:00:00.000+07:00",
                "starts_at": "2024-06-27T12:00:00.000+07:00",
                "usage_limit": 2,
                "promotion_category_id": 2,
                "created_at": "2024-06-27T15:17:40.740+07:00",
                "updated_at": "2024-07-12T18:02:50.847+07:00",
                "public_metadata": {}
            },
            "relationships": {
                "default_store": {
                    "data": {
                        "id": "1",
                        "type": "store"
                    }
                }
            }
        },
        {
            "id": "120",
            "type": "promotion",
            "attributes": {
                "name": "20% Off for New Users",
                "description": "Min spend $5",
                "code": "NEW2BM+",
                "expires_at": "2024-06-28T12:00:00.000+07:00",
                "starts_at": "2024-06-27T12:00:00.000+07:00",
                "usage_limit": 10,
                "promotion_category_id": 4,
                "created_at": "2024-06-27T11:25:05.990+07:00",
                "updated_at": "2024-07-02T10:37:40.651+07:00",
                "public_metadata": {}
            },
            "relationships": {
                "default_store": {
                    "data": {
                        "id": "1",
                        "type": "store"
                    }
                }
            }
        },
        {
            "id": "118",
            "type": "promotion",
            "attributes": {
                "name": "PO: 5$ off by Run with Me",
                "description": "Min Spen 2.5$",
                "code": "POMC+",
                "expires_at": "2024-06-30T12:00:00.000+07:00",
                "starts_at": "2024-06-28T12:00:00.000+07:00",
                "usage_limit": 10,
                "promotion_category_id": 2,
                "created_at": "2024-06-13T20:28:12.727+07:00",
                "updated_at": "2024-07-02T10:38:40.855+07:00",
                "public_metadata": {}
            },
            "relationships": {
                "default_store": {
                    "data": {
                        "id": "1",
                        "type": "store"
                    }
                }
            }
        },
        {
            "id": "109",
            "type": "promotion",
            "attributes": {
                "name": "Student Ticket Promotion 10% off",
                "description": "MIn Spen 0.5$",
                "code": "STUDENT",
                "expires_at": "2024-07-19T12:00:00.000+07:00",
                "starts_at": "2024-07-03T12:00:00.000+07:00",
                "usage_limit": null,
                "promotion_category_id": null,
                "created_at": "2024-02-02T12:35:48.177+07:00",
                "updated_at": "2024-07-03T09:53:08.884+07:00",
                "public_metadata": {}
            },
            "relationships": {
                "default_store": {
                    "data": {
                        "id": "1",
                        "type": "store"
                    }
                }
            }
        }
    ],
    "included": [
        {
            "id": "1",
            "type": "store",
            "attributes": {
                "term_and_condition_promotion": "<p>- 20% Off for New Users: Get a 20% discount on your first purchase.</p>\r\n<p>- Use Code: <strong>NEW2BM+</strong>: Enter code \"<strong>NEW2BM+</strong>\" at checkout.</p>\r\n<p>- Minimum Order <strong>$10</strong>: Minimum purchase of <strong>$10</strong> required.</p>\r\n<p>- Eligibility: Offer valid for new users only.</p>\r\n<p>- One-Time Use: Code can only be used once per user.</p>\r\n<p>- No Stackable Offers: Cannot be combined with other promotions.</p>\r\n<p>- Expiration: Promotion subject to change or termination.</p>\r\n<p>- Non-Transferable: Code has no cash value, non-transferable.</p>"
            }
        }
    ],
    "meta": {
        "count": 4,
        "total_count": 4,
        "total_pages": 1
    },
    "links": {
        "self": "http://127.0.0.1:4000//api/v2/storefront/user_promotion?include=default_store",
        "next": "http://127.0.0.1:4000/api/v2/storefront/user_promotion?include=default_store&page=1",
        "prev": "http://127.0.0.1:4000/api/v2/storefront/user_promotion?include=default_store&page=1",
        "last": "http://127.0.0.1:4000/api/v2/storefront/user_promotion?include=default_store&page=1",
        "first": "http://127.0.0.1:4000/api/v2/storefront/user_promotion?include=default_store&page=1"
    }
}
```

2024-07-02 14:03 UTC, channainfo requested changes

2024-07-02 14:04 UTC, channainfo requested changes

2024-07-02 14:04 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/promo_codes_controller.rb
> +              .pluck('spree_promotions.id')
This method can not be paginated and cause trouble if the dataset is huge

2024-07-03 01:53 UTC, Sreyleak-Deth commented on app/controllers/spree/api/v2/storefront/promo_codes_controller.rb
> +            Spree::PromotionRuleUser
> Create a custom relation instead. we prefer accessing promotion from spree_current_user.xxx instead.

Noted Bong. I will resolve it again.

2024-07-03 10:27 UTC, channainfo requested changes

2024-07-03 10:27 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/promo_codes_controller.rb
> +            @collection ||= spree_current_user.promotions
sort it by newest first.

2024-07-10 03:55 UTC, Thornsopanha commented on app/controllers/spree/api/v2/storefront/promo_codes_controller.rb
created_at change it to id

2024-07-10 06:15 UTC, channainfo requested changes

2024-07-10 06:15 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/promo_codes_controller.rb
> +            Spree::Api::V2::Platform::PromotionSerializer
Do not use this serializer

2024-07-10 13:42 UTC, channainfo requested changes

2024-07-10 13:42 UTC, channainfo commented on app/serializers/spree/v2/storefront/user_promotion_serializer.rb
> +        attribute :default_store do |_object|
Don't use this, use the association and include it instead.

2024-07-10 14:04 UTC, Sreyleak-Deth commented on app/serializers/spree/v2/storefront/user_promotion_serializer.rb
> +        attribute :default_store do |_object|
Noted bong, I will update it

2024-07-12 12:15 UTC, channainfo requested changes

2024-07-12 12:15 UTC, channainfo commented on app/models/spree_cm_commissioner/promotion_decorator.rb
> +    def default_store
Create a custom relation Instead.

2024-07-12 12:15 UTC, channainfo commented on app/serializers/spree/v2/storefront/user_promotion_serializer.rb
> +        has_one :default_store, serializer: Spree::V2::Storefront::StoreSerializer
Create a custom relation instead otherwise it will cause n+1 query

2024-07-16 05:51 UTC, merged