WIP #1632 generate bib number
channainfo/commissioner pull request #1667
Opened 2024-07-18 08:29 UTC by vaneath

2024-07-22 10:45 UTC, channainfo requested changes

2024-07-22 10:45 UTC, channainfo commented on app/jobs/spree_cm_commissioner/generate_bib_number_job.rb
> +      taxon = Spree::Taxon.find(taxon_id)
Move the logic to BibNumberGenerator class and rename this to BibNumberGeneratorJob

2024-07-22 10:49 UTC, channainfo commented
The bib number and the trail should be stored as meta fields in the line items. Storing the bib in the guest is not ideal because not all products require a bib. I think we might not need the bib number auto generated as well.

2024-07-26 05:58 UTC, channainfo commented on app/models/concerns/spree_cm_commissioner/bib_number_concern.rb
> +      after_update :generate_bib_number_job, if: -> { state_changed_to_complete? }
Let's generate bib number only if the product bib prefix is present

2024-07-26 05:58 UTC, channainfo commented on db/migrate/20240726043406_add_partial_unique_index_to_bib_number_and_bib_number_prefix.rb
> +    add_index :cm_guests, [:bib_number, :bib_number_prefix, :event_id],
Let's remove this for now. Create a new ticket for this. The code here is complicated

2024-08-06 06:58 UTC, theachoem commented
If we used this https://github.com/channainfo/commissioner/pull/1705 instead, let's close this PR as duplicate.

2024-08-06 08:05 UTC, vaneath commented
Move to #1705

2024-08-06 08:05 UTC, closed without merging