close #1704 unique bib number event scope
channainfo/commissioner pull request #1705
Opened 2024-07-29 07:45 UTC by vaneath

2024-07-30 02:31 UTC, channainfo requested changes

2024-07-30 02:31 UTC, channainfo commented on app/interactors/spree_cm_commissioner/bib_number_generator.rb
> +        guest.line_item.option_types.any? { |option_type| option_type.name == 'bib-number-prefix' }
let's extract the 
```sh
option_type.name == 'bib-number-prefix'

```
to its own method in the option_type_decorator.rb

```rb
def bib_number_prefix?
  name == 'bib-number-prefix'
end




```

2024-07-30 02:31 UTC, channainfo commented on app/models/spree_cm_commissioner/guest.rb
> +      self.bib_number_prefix = bib_number_prefix
this is confusing. The default bib_number_prefix should only be set once.

2024-07-30 02:31 UTC, channainfo commented on app/models/spree_cm_commissioner/guest.rb
> +    def bib_number_prefix
remove this method it causes confusion.

2024-08-01 08:27 UTC, channainfo requested changes

2024-08-01 08:27 UTC, channainfo commented on app/models/spree_cm_commissioner/guest.rb
> +      return if bib_index.present? && !bib_related_fields_changed?
let's remove this line. the logic here might bring us a false positive result

2024-08-01 08:27 UTC, channainfo commented on app/models/spree_cm_commissioner/guest.rb
> +    def bib_related_fields_changed?
let's remove this. field_changed? is problematic.

2024-08-01 08:27 UTC, channainfo commented on app/models/spree_cm_commissioner/guest.rb
> +      self.bib_index = "#{event_id}-#{bib_number_prefix}-#{bib_number}" if bib_number.present?
If the bib_number field is blank, it should be generated and assigned before saving. We permit this field to be blank because there are occasions when we want to manually assign a value. A more effective approach might involve checking for the presence of bib_number_prefix.

If bib_number_prefix is not blank:

1. Generate bib_number if it is blank.
2. Assign the bib_index using the prefix and the number.

2024-08-01 08:27 UTC, channainfo commented on app/models/spree_cm_commissioner/guest.rb
> +    def generate_bib_number
create two method generate_bib_number and generate_bib_number!

generate_bib_number return the next bib_number 

and 
```rb
def generate_bib_number!
  bib_number = generate_bib_number
  save!
end
```

2024-08-01 08:27 UTC, channainfo commented on app/models/spree_cm_commissioner/guest.rb
> +    def full_bib_number
use bib_number_with_prefix instead.

2024-08-01 08:27 UTC, channainfo commented on app/models/spree_cm_commissioner/option_type_decorator.rb
> +      def bib_number_prefix?
Maybe bib_prefix sounds more consistent

2024-08-03 03:15 UTC, vaneath commented on app/models/spree_cm_commissioner/guest.rb
> +      self.bib_index = "#{event_id}-#{bib_number_prefix}-#{bib_number}" if bib_number.present?
Hi bong, thank for reviewing. But I am not quite sure what you mean here, I have resolved most of your comment, but I am still misunderstanding with this. According to what I know, bib_number should only be generated when conditions are meet. Example: kyc is enable and the option_type has bib-prefix-number, otherwise it will be blank. Could you me the example of can I implement this bong?

2024-08-08 03:31 UTC, channainfo commented on app/models/spree_cm_commissioner/guest.rb
> +      self.bib_index = "#{event_id}-#{bib_number_prefix}-#{bib_number}" if bib_number.present?
rename bib_number_prefix to bib_prefix

2024-08-08 04:48 UTC, channainfo requested changes

2024-08-09 06:39 UTC, channainfo requested changes

2024-08-09 06:39 UTC, channainfo commented on app/interactors/spree_cm_commissioner/bib_generator.rb
> +      return unless taxon
let's do this instead
```
context.fail!(message: "invalid taxon event with id: #{taxon_id}") if taxon.blank?
```

2024-08-09 06:39 UTC, channainfo commented on app/models/spree_cm_commissioner/guest.rb
> +    scope :none_bib, -> { where(bib_prefix: [nil, '']).order(created_at: :asc) }
let's remove order(created_at: :asc) from the scope. we should call the order  in the service instead.

2024-08-09 06:39 UTC, channainfo commented on app/interactors/spree_cm_commissioner/bib_generator.rb
> +      taxon.guests.includes(line_item: :variant).none_bib.find_each(&:generate_bib!)
# order the record by id is more efficient.
taxon.guests.includes(line_item: :variant).none_bib.order('id ASC').find_each(&:generate_bib!)

2024-08-11 08:00 UTC, theachoem requested changes

2024-08-11 08:00 UTC, theachoem commented on app/models/spree_cm_commissioner/guest.rb
> +      "#{bib_prefix}#{bib_number}"
I think solution_2 is better for us, since we want to use them as seat as well. But we have to aware of its CONS.

2024-08-12 02:03 UTC, vaneath commented on app/models/spree_cm_commissioner/guest.rb
> +      "#{bib_prefix}#{bib_number}"
Noted, brother

2024-08-13 13:16 UTC, merged