WIP #1719 allow customer to have recurring promotion
channainfo/commissioner pull request #1720
Opened 2024-08-01 07:32 UTC by tykealy

2024-08-01 14:06 UTC, channainfo requested changes

2024-08-01 14:06 UTC, channainfo commented on spec/interactors/spree_cm_commissioner/customer_promotion_creator_spec.rb
> +      it "creates a new promotion" do
add a case where customer is not found

2024-08-02 14:17 UTC, channainfo commented
@tykealy let's rebase this with develop. the number of commits here is overwhelming

2024-08-05 05:07 UTC, tykealy commented
> @tykealy let's rebase this with develop. the number of commits here is overwhelming

@channainfo, I've rebased with develop bong.

2024-08-07 10:29 UTC, channainfo requested changes

2024-08-07 10:29 UTC, channainfo commented on db/migrate/20240730073727_create_super_admin_role.rb
> +    super_admin = Spree::Role.find_or_create_by(name: 'super_admin')
Remove this migration.  Do it via rails console instead.

2024-08-07 11:00 UTC, merged