Close #1963 Change the status from event_status to badge_status
channainfo/commissioner pull request #1964
Opened 2024-09-19 04:53 UTC by DethSreyleak

2024-09-19 10:43 UTC, channainfo requested changes

2024-09-19 10:43 UTC, channainfo commented on db/migrate/20240907061117_add_show_event_status_to_spree_taxon.rb
> -    add_column :spree_taxons, :show_event_status, :boolean, if_not_exists: true
Don't delete this file

2024-09-19 10:43 UTC, channainfo commented on db/migrate/20240907061117_add_badge_status_to_spree_taxon.rb
> +    add_column :spree_taxons, :badge_status, :boolean, if_not_exists: true
use the rename column instead.  let's call it show_badge_status and default to the false value

2024-09-19 10:43 UTC, channainfo commented on app/overrides/spree/admin/taxons/_form/badge_status.html.erb.deface
> +        { include_blank: 'None' },
remove include blank. by default is Off ( false)

2024-09-19 10:44 UTC, channainfo commented on app/overrides/spree/admin/taxons/_form/badge_status.html.erb.deface
> +        { include_blank: 'None' },
@Sreyleak-Deth make sure you test db:migrate and db:rollback to ensure they work correctly

2024-09-19 11:01 UTC, Sreyleak-Deth commented
Note bong, I will check it again

On Thu, Sep 19, 2024, 5:44 PM Channa Ly ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In app/overrides/spree/admin/taxons/_form/badge_status.html.erb.deface
> <https://github.com/channainfo/commissioner/pull/1964#discussion_r1766610711>
> :
>
> > @@ -0,0 +1,11 @@
> +<!-- insert_before "erb[loud]:contains('field_container :parent_id')" -->
> +
> +<%= f.field_container :badge_status do %>
> +  <%= f.label :badge_status, Spree.t('badge_status'), class: 'form-label' %>
> +  <%= f.select :badge_status,
> +        options_for_select([['On', true], ['Off', false]], f.object.badge_status),
> +        { include_blank: 'None' },
>
> @Sreyleak-Deth <https://github.com/Sreyleak-Deth> make sure you test
> db:migrate and db:rollback to ensure they work correctly
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/channainfo/commissioner/pull/1964#discussion_r1766610711>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3UEJP5DOVO2AUEBCZFNUVLZXKTJHAVCNFSM6AAAAABOPB3T3SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMJVGE2TMOJTGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-09-25 09:42 UTC, channainfo requested changes

2024-09-25 09:42 UTC, channainfo commented on db/migrate/20240907061117_add_show_badge_status_to_spree_taxon.rb
> +    add_column :spree_taxons, :show_badge_status, :boolean, default: false, if_not_exists: true
We already have a column for this, so why not rename the existing column instead of creating a new one?

2024-09-25 09:57 UTC, Sreyleak-Deth commented on db/migrate/20240907061117_add_show_badge_status_to_spree_taxon.rb
> +    add_column :spree_taxons, :show_badge_status, :boolean, default: false, if_not_exists: true
> We already have a column for this, so why not rename the existing column instead of creating a new one?

The original column was named show_event_status, and based on your suggestion, I have renamed it to show_badge_status.

2024-10-07 11:04 UTC, channainfo requested changes

2024-10-07 11:04 UTC, channainfo commented on db/migrate/20240926035819_rename_show_event_status_to_show_badge_status_to_spree_taxon.rb
> +    change_column :spree_taxons, :show_badge_status, :boolean, default: false, if_not_exists: true
remove the if_not_exists: true.
```
change_column :spree_taxons, :show_badge_status, :boolean, default: false
```

2024-10-07 13:10 UTC, Sreyleak-Deth commented on db/migrate/20240926035819_rename_show_event_status_to_show_badge_status_to_spree_taxon.rb
> +    change_column :spree_taxons, :show_badge_status, :boolean, default: false, if_not_exists: true
> remove the if_not_exists: true.
> 
> ```
> change_column :spree_taxons, :show_badge_status, :boolean, default: false
> ```

it has fixed bong

2024-10-09 07:12 UTC, merged