WIP #1979 create new api for organizer profile
channainfo/commissioner pull request #1980
Opened 2024-09-27 03:01 UTC by Sreyleak-Deth

2024-11-07 13:46 UTC, channainfo requested changes

2024-11-07 13:46 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/events_controller.rb
> +            @vendor ||= Spree::Vendor.find_by(id: params[:vendor_id])
Why you need this?

2024-11-07 13:46 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/events_controller.rb
> +              vendor_id: vendor.id,
Use the value from the params

2024-11-07 13:46 UTC, channainfo commented on app/queries/spree_cm_commissioner/organizer_profile_event_query.rb
> +      if section == 'upcoming'
Let's have the options for previous, upcoming and all

2024-11-08 01:50 UTC, Sreyleak-Deth commented on app/controllers/spree/api/v2/storefront/events_controller.rb
> +            @vendor ||= Spree::Vendor.find_by(id: params[:vendor_id])
> Why you need this?

Because We need Calls the vendor method to get the vendor ID for the organizer_query:

```
organizer_query = SpreeCmCommissioner::OrganizerProfileEventQuery.new(
              vendor_id: vendor.id,
              section: params[:section] || 'upcoming'
            )
```

2024-11-08 01:53 UTC, Sreyleak-Deth commented on app/controllers/spree/api/v2/storefront/events_controller.rb
> +              vendor_id: vendor.id,
> Use the value from the params

Noted bong,I will correct it

2024-11-08 01:54 UTC, Sreyleak-Deth commented on app/queries/spree_cm_commissioner/organizer_profile_event_query.rb
> +      if section == 'upcoming'
> 

ok bong, i will update it again

2024-11-08 10:53 UTC, channainfo commented
@Sreyleak-Deth it seems that you have the n+1 for the ActiveStorage for both the Blob and Attachement.

2024-11-12 01:40 UTC, Sreyleak-Deth commented
### When not include the 
.includes(
                             icon: :attachment_attachment,
                             category_icon: :attachment_attachment,
                             web_banner: :attachment_attachment,
                             home_banner: :attachment_attachment,
                             app_banner: :attachment_attachment
                           )

``` json
2024-11-12 08:37:54.640326 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (2.661ms) ActiveRecord -- Spree::Taxon Count -- { :sql => "SELECT COUNT(*) FROM (SELECT 1 AS one FROM \"spree_taxons\" WHERE \"spree_taxons\".\"vendor_id\" = $1 AND (to_date >= '2024-11-12 01:37:54.468148') ORDER BY \"spree_taxons\".\"from_date\" ASC LIMIT $2 OFFSET $3) subquery_for_count", :binds => { :vendor_id => 9, :limit => 25, :offset => 0 }, :allocations => 567, :cached => nil }
2024-11-12 08:37:54.644045 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (2.737ms) ActiveRecord -- Spree::Taxon Load -- { :sql => "SELECT \"spree_taxons\".* FROM \"spree_taxons\" WHERE \"spree_taxons\".\"vendor_id\" = $1 AND (to_date >= '2024-11-12 01:37:54.468148') ORDER BY \"spree_taxons\".\"from_date\" ASC LIMIT $2 OFFSET $3", :binds => { :vendor_id => 9, :limit => 25, :offset => 0 }, :allocations => 579, :cached => nil }
2024-11-12 08:37:54.675552 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (2.907ms) ActiveRecord -- Spree::Taxon Load -- { :sql => "SELECT \"spree_taxons\".* FROM \"spree_taxons\" WHERE \"spree_taxons\".\"lft\" <= 122 AND \"spree_taxons\".\"rgt\" >= 125 AND (\"spree_taxons\".\"id\" != 358) ORDER BY lft", :allocations => 232, :cached => nil }
2024-11-12 08:37:54.683351 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (1.512ms) ActiveRecord -- Spree::Taxon Pluck -- { :sql => "SELECT \"spree_taxons\".\"id\" FROM \"spree_taxons\" WHERE \"spree_taxons\".\"parent_id\" = $1", :binds => { :parent_id => 358 }, :allocations => 216, :cached => nil }
2024-11-12 08:37:54.702815 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (4.160ms) ActiveRecord -- Spree::TaxonImage Load -- { :sql => "SELECT \"spree_assets\".* FROM \"spree_assets\" WHERE \"spree_assets\".\"type\" = $1 AND \"spree_assets\".\"viewable_id\" = $2 AND \"spree_assets\".\"viewable_type\" = $3 LIMIT $4", :binds => { :type => "Spree::TaxonImage", :viewable_id => 358, :viewable_type => "Spree::Taxon", :limit => 1 }, :allocations => 233, :cached => nil }
2024-11-12 08:37:54.742977 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (6.776ms) ActiveRecord -- Spree::Vendor Pluck -- { :sql => "SELECT \"spree_vendors\".\"id\" FROM \"spree_vendors\" INNER JOIN \"cm_taxon_vendors\" ON \"spree_vendors\".\"id\" = \"cm_taxon_vendors\".\"vendor_id\" WHERE \"spree_vendors\".\"deleted_at\" IS NULL AND \"cm_taxon_vendors\".\"taxon_id\" = $1", :binds => { :taxon_id => 358 }, :allocations => 217, :cached => nil }
2024-11-12 08:37:54.765989 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (7.802ms) ActiveRecord -- Spree::Product Pluck -- { :sql => "SELECT \"spree_products\".\"id\" FROM \"spree_products\" INNER JOIN \"spree_products_taxons\" ON \"spree_products\".\"id\" = \"spree_products_taxons\".\"product_id\" WHERE \"spree_products\".\"deleted_at\" IS NULL AND \"spree_products_taxons\".\"taxon_id\" = $1 AND \"spree_products_taxons\".\"visible\" = $2 ORDER BY \"spree_products_taxons\".\"position\" ASC", :binds => { :taxon_id => 358, :visible => true }, :allocations => 217, :cached => nil }
2024-11-12 08:37:54.780977 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (2.323ms) ActiveRecord -- SpreeCmCommissioner::TaxonCategoryIcon Load -- { :sql => "SELECT \"spree_assets\".* FROM \"spree_assets\" WHERE \"spree_assets\".\"type\" = $1 AND \"spree_assets\".\"viewable_id\" = $2 AND \"spree_assets\".\"viewable_type\" = $3 LIMIT $4", :binds => { :type => "SpreeCmCommissioner::TaxonCategoryIcon", :viewable_id => 358, :viewable_type => "Spree::Taxon", :limit => 1 }, :allocations => 233, :cached => nil }
2024-11-12 08:37:55.033688 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (3.290ms) ActiveRecord -- ActiveStorage::Attachment Load -- { :sql => "SELECT \"active_storage_attachments\".* FROM \"active_storage_attachments\" WHERE \"active_storage_attachments\".\"record_type\" = $1 AND \"active_storage_attachments\".\"name\" = $2 AND \"active_storage_attachments\".\"record_id\" = $3", :binds => { :record_type => "Spree::Asset", :name => "attachment", :record_id => 1329 }, :allocations => 252, :cached => nil }
2024-11-12 08:37:55.060500 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (2.994ms) ActiveRecord -- ActiveStorage::Blob Load -- { :sql => "SELECT \"active_storage_blobs\".* FROM \"active_storage_blobs\" WHERE \"active_storage_blobs\".\"id\" = $1", :binds => { :id => 3522 }, :allocations => 248, :cached => nil }
2024-11-12 08:37:55.076216 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (1.648ms) ActiveRecord -- SpreeCmCommissioner::TaxonAppBanner Load -- { :sql => "SELECT \"spree_assets\".* FROM \"spree_assets\" WHERE \"spree_assets\".\"type\" = $1 AND \"spree_assets\".\"viewable_id\" = $2 AND \"spree_assets\".\"viewable_type\" = $3 LIMIT $4", :binds => { :type => "SpreeCmCommissioner::TaxonAppBanner", :viewable_id => 358, :viewable_type => "Spree::Taxon", :limit => 1 }, :allocations => 378, :cached => nil }
2024-11-12 08:37:55.090841 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (3.158ms) ActiveRecord -- ActiveStorage::Attachment Load -- { :sql => "SELECT \"active_storage_attachments\".* FROM \"active_storage_attachments\" WHERE \"active_storage_attachments\".\"record_type\" = $1 AND \"active_storage_attachments\".\"name\" = $2 AND \"active_storage_attachments\".\"record_id\" = $3", :binds => { :record_type => "Spree::Asset", :name => "attachment", :record_id => 1330 }, :allocations => 660, :cached => nil }
2024-11-12 08:37:55.095771 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (3.171ms) ActiveRecord -- ActiveStorage::Blob Load -- { :sql => "SELECT \"active_storage_blobs\".* FROM \"active_storage_blobs\" WHERE \"active_storage_blobs\".\"id\" = $1", :binds => { :id => 3523 }, :allocations => 616, :cached => nil }
2024-11-12 08:37:55.104092 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (2.464ms) ActiveRecord -- SpreeCmCommissioner::TaxonWebBanner Load -- { :sql => "SELECT \"spree_assets\".* FROM \"spree_assets\" WHERE \"spree_assets\".\"type\" = $1 AND \"spree_assets\".\"viewable_id\" = $2 AND \"spree_assets\".\"viewable_type\" = $3 LIMIT $4", :binds => { :type => "SpreeCmCommissioner::TaxonWebBanner", :viewable_id => 358, :viewable_type => "Spree::Taxon", :limit => 1 }, :allocations => 373, :cached => nil }
2024-11-12 08:37:55.118946 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (2.048ms) ActiveRecord -- ActiveStorage::Attachment Load -- { :sql => "SELECT \"active_storage_attachments\".* FROM \"active_storage_attachments\" WHERE \"active_storage_attachments\".\"record_type\" = $1 AND \"active_storage_attachments\".\"name\" = $2 AND \"active_storage_attachments\".\"record_id\" = $3", :binds => { :record_type => "Spree::Asset", :name => "attachment", :record_id => 1331 }, :allocations => 457, :cached => nil }
2024-11-12 08:37:55.123793 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5a-e458bbd262bf} (3.399ms) ActiveRecord -- ActiveStorage::Blob Load -- { :sql => "SELECT \"active_storage_blobs\".* FROM \"active_storage_blobs\" WHERE \"active_storage_blobs\".\"id\" = $1", :binds => { :id => 3524 }, :allocations => 819, :cached => nil }
2024-11-12 08:37:55.133354 D [12982:puma srv tp 002] {request_id: 6902d5cb-ce5d-409d-8a5 [...]

2024-11-12 01:43 UTC, Sreyleak-Deth commented
### When we included all the icon and image below it solved the old issue but it got new one issue:

taxons = Spree::Taxon.where(vendor_id: vendor_id)
                           .includes(
                             icon: :attachment_attachment,
                             category_icon: :attachment_attachment,
                             web_banner: :attachment_attachment,
                             home_banner: :attachment_attachment,
                             app_banner: :attachment_attachment
                           )

```
2024-11-12 08:42:12.698004 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (1.988ms) ActiveRecord -- Spree::Taxon Count -- { :sql => "SELECT COUNT(*) FROM (SELECT 1 AS one FROM \"spree_taxons\" WHERE \"spree_taxons\".\"vendor_id\" = $1 AND (to_date >= '2024-11-12 01:42:12.580591') ORDER BY \"spree_taxons\".\"from_date\" ASC LIMIT $2 OFFSET $3) subquery_for_count", :binds => { :vendor_id => 9, :limit => 25, :offset => 0 }, :allocations => 522, :cached => nil }
2024-11-12 08:42:12.700948 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.294ms) ActiveRecord -- Spree::Taxon Load -- { :sql => "SELECT \"spree_taxons\".* FROM \"spree_taxons\" WHERE \"spree_taxons\".\"vendor_id\" = $1 AND (to_date >= '2024-11-12 01:42:12.580591') ORDER BY \"spree_taxons\".\"from_date\" ASC LIMIT $2 OFFSET $3", :binds => { :vendor_id => 9, :limit => 25, :offset => 0 }, :allocations => 768, :cached => nil }
2024-11-12 08:42:12.798722 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (1.736ms) ActiveRecord -- Spree::TaxonImage Load -- { :sql => "SELECT \"spree_assets\".* FROM \"spree_assets\" WHERE \"spree_assets\".\"type\" = $1 AND \"spree_assets\".\"viewable_type\" = $2 AND \"spree_assets\".\"viewable_id\" IN ($3, $4)", :binds => { :type => "Spree::TaxonImage", :viewable_type => "Spree::Taxon", :viewable_id => [ 358, 74 ] }, :allocations => 231, :cached => nil }
2024-11-12 08:42:12.801265 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (1.805ms) ActiveRecord -- SpreeCmCommissioner::TaxonCategoryIcon Load -- { :sql => "SELECT \"spree_assets\".* FROM \"spree_assets\" WHERE \"spree_assets\".\"type\" = $1 AND \"spree_assets\".\"viewable_type\" = $2 AND \"spree_assets\".\"viewable_id\" IN ($3, $4)", :binds => { :type => "SpreeCmCommissioner::TaxonCategoryIcon", :viewable_type => "Spree::Taxon", :viewable_id => [ 358, 74 ] }, :allocations => 641, :cached => nil }
2024-11-12 08:42:12.841037 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.356ms) ActiveRecord -- ActiveStorage::Attachment Load -- { :sql => "SELECT \"active_storage_attachments\".* FROM \"active_storage_attachments\" WHERE \"active_storage_attachments\".\"record_type\" = $1 AND \"active_storage_attachments\".\"name\" = $2 AND \"active_storage_attachments\".\"record_id\" IN ($3, $4)", :binds => { :record_type => "Spree::Asset", :name => "attachment", :record_id => [ 770, 1329 ] }, :allocations => 250, :cached => nil }
2024-11-12 08:42:12.863952 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (1.960ms) ActiveRecord -- ActiveStorage::Blob Load -- { :sql => "SELECT \"active_storage_blobs\".* FROM \"active_storage_blobs\" WHERE \"active_storage_blobs\".\"id\" IN ($1, $2)", :binds => { :id => [ 2245, 3522 ] }, :allocations => 246, :cached => nil }
2024-11-12 08:42:12.871485 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.602ms) ActiveRecord -- SpreeCmCommissioner::TaxonWebBanner Load -- { :sql => "SELECT \"spree_assets\".* FROM \"spree_assets\" WHERE \"spree_assets\".\"type\" = $1 AND \"spree_assets\".\"viewable_type\" = $2 AND \"spree_assets\".\"viewable_id\" IN ($3, $4)", :binds => { :type => "SpreeCmCommissioner::TaxonWebBanner", :viewable_type => "Spree::Taxon", :viewable_id => [ 358, 74 ] }, :allocations => 549, :cached => nil }
2024-11-12 08:42:12.884207 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (1.943ms) ActiveRecord -- ActiveStorage::Attachment Load -- { :sql => "SELECT \"active_storage_attachments\".* FROM \"active_storage_attachments\" WHERE \"active_storage_attachments\".\"record_type\" = $1 AND \"active_storage_attachments\".\"name\" = $2 AND \"active_storage_attachments\".\"record_id\" IN ($3, $4)", :binds => { :record_type => "Spree::Asset", :name => "attachment", :record_id => [ 771, 1331 ] }, :allocations => 648, :cached => nil }
2024-11-12 08:42:12.888264 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.624ms) ActiveRecord -- ActiveStorage::Blob Load -- { :sql => "SELECT \"active_storage_blobs\".* FROM \"active_storage_blobs\" WHERE \"active_storage_blobs\".\"id\" IN ($1, $2)", :binds => { :id => [ 2246, 3524 ] }, :allocations => 644, :cached => nil }
2024-11-12 08:42:12.893078 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.356ms) ActiveRecord -- SpreeCmCommissioner::TaxonHomeBanner Load -- { :sql => "SELECT \"spree_assets\".* FROM \"spree_assets\" WHERE \"spree_assets\".\"type\" = $1 AND \"spree_assets\".\"viewable_type\" = $2 AND \"spree_assets\".\"viewable_id\" IN ($3, $4)", :binds => { :type => "SpreeCmCommissioner::TaxonHomeBanner", :viewable_type => "Spree::Taxon", :viewable_id => [ 358, 74 ] }, :allocations => 549, :cached => nil }
2024-11-12 08:42:12.907821 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.803ms) ActiveRecord -- ActiveStorage::Attachment Load -- { :sql => "SELECT \"active_storage_attachments\".* FROM \"active_storage_attachments\" WHERE \"active_storage_attachments\".\"record_type\" = $1 AND \"active_storage_attachments\".\"name\" = $2 AND \"active_storage_attachments\".\"record_id\" = $3", :binds => { :record_type => "Spree::Asset", :name => "attachment", :record_id => 1332 }, :allocations => 250, :cached => nil }
2024-11-12 08:42:12.912305 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (1.558ms) ActiveRecord -- ActiveStorage::Blob Load -- { :sql => "SELECT \"active_storage_blobs\".* FROM \"active_storage_blobs\" WHERE \"active_storage_blobs\".\"id\" = $1", :binds => { :id => 3525 }, :allocations => 246, :cached => nil }
2024-11-12 08:42:12.915562 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.070ms) ActiveRecord -- SpreeCmCommissioner::TaxonAppBanner Load -- { :sql => "SELECT \"spree_assets\".* FROM \"spree_assets\" WHERE \"spree_assets\".\"type\" = $1 AND \"spree_assets\".\"viewable_type\" = $2 AND \"spree_assets\".\"viewable_id\" IN ($3, $4)", :binds => { :type => "SpreeCmCommissioner::TaxonAppBanner", :viewable_type => "Spree::Taxon", :viewable_id => [ 358, 74 ] }, :allocations => 519, :cached => nil }
2024-11-12 08:42:12.929944 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.289ms) ActiveRecord -- ActiveStorage::Attachment Load -- { :sql => "SELECT \"active_storage_attachments\".* FROM \"active_storage_attachments\" WHERE \"active_storage_attachments\".\"record_type\" = $1 AND \"active_storage_attachments\".\"name\" = $2 AND \"active_storage_attachments\".\"record_id\" IN ($3, $4)", :binds => { :record_type => "Spree::Asset", :name => "attachment", :record_id => [ 772, 1330 ] }, :allocations => 648, :cached => nil }
2024-11-12 08:42:12.933642 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.158ms) ActiveRecord -- ActiveStorage::Blob Load -- { :sql => "SELECT \"active_storage_blobs\".* FROM \"active_storage_blobs\" WHERE \"active_storage_blobs\".\"id\" IN ($1, $2)", :binds => { :id => [ 2247, 3523 ] }, :allocations => 644, :cached => nil }
2024-11-12 08:42:12.944900 D [12982:puma srv tp 004] {request_id: 984e11e3-0780-4c42-897a-74bfeab69f0e} (2.759ms) ActiveRecord -- Spree::Taxon Load -- { :sql => "SELECT \"spree_taxons\".* FROM \"spree_taxons\" WHERE \"spree_taxons\".\"lft\" <= 122 AND \"s [...]

2024-12-03 07:31 UTC, merged