WIP #1968 implement Saved Guests
channainfo/commissioner pull request #1981
Opened 2024-09-27 04:38 UTC by LengTech11

2024-10-16 09:46 UTC, channainfo requested changes

2024-10-16 09:46 UTC, channainfo commented on lib/tasks/migrate_id_cards.rake
> +    class CmIdCard < ApplicationRecord
Remove this. Model should be defined under the models/

2024-10-16 09:48 UTC, channainfo requested changes

2024-10-16 09:48 UTC, channainfo commented on lib/tasks/migrate_id_cards.rake
> +  task migrate_id_cards: :environment do
How to get this task gets run?

2024-10-16 10:00 UTC, LengTech11 commented on lib/tasks/migrate_id_cards.rake
> +  task migrate_id_cards: :environment do
Add this to cm_server as normal bong
```rb

_migrate_id_cards:
  status: disabled
  cron: "0 0 * * *"
  class: InvokeRakeTaskCron
  args:
    task: spree_cm_commissioner:migrate_id_cards

```

2024-10-16 10:29 UTC, LengTech11 commented on lib/tasks/migrate_id_cards.rake
> +    class CmIdCard < ApplicationRecord
i do this instead bong
```rb
task migrate_id_cards: :environment do
    SpreeCmCommissioner::IdCard.reset_column_information
    SpreeCmCommissioner::IdCard.where.not(guest_id: nil).find_each do |id_card|
      id_card.update(id_cardable_type: 'SpreeCmCommissioner::Guest', id_cardable_id: id_card.guest_id)
    end
  end
 ```

2024-10-17 04:39 UTC, channainfo requested changes

2024-10-17 04:39 UTC, channainfo commented on db/migrate/20240926100138_create_spree_cm_commissioner_template_guests.rb
> +      t.boolean :default, default: false
rename from default to is_default? and add more fields from the guest table

2024-10-17 04:39 UTC, channainfo commented on lib/tasks/migrate_id_cards.rake
> +    SpreeCmCommissioner::IdCard.reset_column_information
remove this.

2024-10-17 07:03 UTC, LengTech11 commented on db/migrate/20240926100138_create_spree_cm_commissioner_template_guests.rb
> +      t.boolean :default, default: false
i had add phone_number and emergency_contact.

2024-10-21 02:15 UTC, merged