[WIP] Search and return inventory
channainfo/commissioner pull request #20
Opened 2022-11-21 06:20 UTC by kimsrung

2022-11-23 07:25 UTC, channainfo commented
@kimsrung add rake commands to README under the Seed sub section.

2022-11-23 12:39 UTC, channainfo requested changes

2022-11-25 01:46 UTC, channainfo requested changes

2022-11-25 01:46 UTC, channainfo commented on app/models/spree/product_decorator.rb
> +      option_value = option_type.option_values.find_by!(state_id: location.state_id)
we don't need to have state_id in the option_values. This field in which is very little in use and other records will carry on with. we can just store the state_id in the **value** field

2022-11-25 01:46 UTC, channainfo commented on db/migrate/20221121012928_add_state_id_to_option_value.rb
> +    add_column :spree_option_values, :state_id, :bigint
Let's remove this.

2022-11-25 03:35 UTC, channainfo requested changes

2022-11-25 03:35 UTC, channainfo commented on lib/tasks/kh_provinces.rake
> +    cambodia.states.create!([
@kimsrung let's also make this idempotent. It is ok to do them one by one without bulk insert since it is relatively small. We want to make sure they are safe to run multiple times.

2022-11-25 03:35 UTC, channainfo commented on spec/models/spree/product_spec.rb
> +  describe 'callback #create_location' do
let's just use solely #create_location. You can either remove the **callback** text or create a nested block:

```
description 'callback' do
   description '#create_location' do

```

2022-11-25 03:35 UTC, channainfo commented on lib/tasks/kh_location_option_values.rake
> +      location_type.option_values.find_or_create_by!(name: province.name, presentation: province.id)
let's use find_or_initalize_by to make it idempotent.

2022-11-25 03:35 UTC, channainfo commented on lib/tasks/kh_location_option_values.rake
> +    location_type = Spree::OptionType.find_or_create_by!(name: 'location', presentation: 'Location', attr_type: 'state_selection')
let's use find_or_initalize_by to make it idempotent.

2022-11-25 03:35 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/search_controller.rb
> +            @collection ||= scope.ransack(stock_locations_state_id_eq: province_id).result(distinct: true)
let's make province id optional. if the province is not provided we return all.

2022-11-25 03:35 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/search_controller.rb
> +            raise ActionController::ParameterMissing if params[:province_id].blank?
for now, we can just ignore this line.

2022-11-28 03:06 UTC, theachoem approved these changes

2022-11-28 03:07 UTC, theachoem approved these changes
Just check whether it not conflict with our discussed flow here: https://github.com/channainfo/commissioner/issues/19

2022-11-29 09:35 UTC, channainfo requested changes

2022-11-29 09:35 UTC, channainfo commented on app/models/spree/product_decorator.rb
> +      option_type = Spree::OptionType.find_by!(name: 'location', presentation: 'Location', attr_type: 'state_selection')
always use ** find_or_initialize_by** instead -- create if it does not exist, otherwise, read. 

This will make sure we will be able to run the code without waiting for the rake task to have been run ahead, especially when new data is added and the rake task has already run before.

2022-11-29 09:35 UTC, channainfo commented on app/models/spree/product_decorator.rb
> +      option_value = option_type.option_values.find_by!(presentation: location.state_id)
use find_by_or_initialize instead. Create if it does not exist, otherwise, read.

2022-11-29 09:35 UTC, channainfo commented on lib/tasks/kh_location_option_values.rake
> +    cambodia = Spree::Country.find_by!(name: 'Cambodia')  # run `rake data:seed_kh_provinces` first
This case is a bit more specific but let's just use find_or_initialize_by here too following the same principle above. Let's use the **abbr** field instead. The **name** might be subjected to translation or use Country.cambodia

2022-11-29 10:36 UTC, kimsrung commented on lib/tasks/kh_location_option_values.rake
> +    cambodia = Spree::Country.find_by!(name: 'Cambodia')  # run `rake data:seed_kh_provinces` first
Spree doesn't have **abbr** field, it uses as **iso**. I will update that. But I just want to prefer to use ** find_or_create_by** instead

2022-11-30 04:05 UTC, merged