Close #206 get nearby places from google api
channainfo/commissioner pull request #207
Opened 2023-02-28 09:09 UTC by panhachom

### Task Breakdown 
- Get nearby places from google API (min : 20 places , max : 60 places)
- Calculate  distance between places and vendor

2023-03-01 07:21 UTC, kimsrung commented on app/controllers/spree/admin/nearby_places_controller.rb
> +        @object ||= @vendor
to save this, we can just have @object then in our form @vendor => @object.

2023-03-01 07:35 UTC, kimsrung commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +      url = URI("https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=#{vendor.lat}%2C#{vendor.lon}&radius=5000&key=#{google_map_key}")
maybe we can create a variable called GOOGLE_MAP_API_URL="https://maps.googleapis.com/maps/api"

later if you have another feature like find_place, we can reuse that constant from env

2023-03-01 08:42 UTC, kimsrung commented on config/routes.rb
>            post :update_positions
you can remove post :update_positions . it's not necessary after adding patch :update_position. Please help to verify

2023-03-01 08:44 UTC, kimsrung commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +    GOOGLE_MAP_API_URL = 'https://maps.googleapis.com/maps/api'.freeze
I'd prefer this in .env . what would you think?

2023-03-01 08:46 UTC, kimsrung commented on app/controllers/spree/admin/nearby_places_controller.rb
> +        promoted_nearby_place_ids = promoted_nearby_place_ids.map(&:to_i)
promoted_nearby_place_ids = params['vendor']['promoted_nearby_place_ids'].map(&:to_i)

maybe we can just assign 1 time here. Assigning multiple time with the same name is little bit confusing since it's not a long method

2023-03-01 09:12 UTC, panhachom commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +    GOOGLE_MAP_API_URL = 'https://maps.googleapis.com/maps/api'.freeze
since there is no .env file  in commissioner, I think it is much easy to call the variable here

2023-03-01 15:14 UTC, channainfo requested changes

2023-03-01 15:14 UTC, channainfo commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +      json_response['results'].each_with_index do |json, index|
We should not save the place from search but to save only those were selected

2023-03-01 15:14 UTC, channainfo commented on config/routes.rb
> +          patch :update
remove this. the **update** is a built in

2023-03-02 01:16 UTC, kimsrung commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +    GOOGLE_MAP_API_URL = 'https://maps.googleapis.com/maps/api'.freeze
what you have done for this ENV.fetch('GOOGLE_MAP_KEY'), you could apply for url as well

2023-03-02 01:22 UTC, theachoem commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +    GOOGLE_MAP_API_URL = 'https://maps.googleapis.com/maps/api'.freeze
It is a constant variable, i don't think putting it in .env is a good idea. If we want to reuse, we can access from here instead.

2023-03-02 06:46 UTC, kimsrung commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +    GOOGLE_MAP_API_URL = 'https://maps.googleapis.com/maps/api'.freeze
so if you have another service for fetching google map api for place search or auto complete, are we going to repeat that URL in each class? 

I was just thinking ahead but if we don't have that feature, we can just add constant there

2023-03-02 06:48 UTC, theachoem commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +    GOOGLE_MAP_API_URL = 'https://maps.googleapis.com/maps/api'.freeze
We can access via sth like this: NearbyPlacesLoader::GOOGLE_MAP_API_URL or put it in another alternative class and access like so. I'm sure most gem do this instead of ask user to put in env.

2023-03-02 07:14 UTC, kimsrung commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +    GOOGLE_MAP_API_URL = 'https://maps.googleapis.com/maps/api'.freeze
if so, we can put in initializers with google_map.rb

2023-03-02 07:15 UTC, theachoem commented on app/interactors/spree_cm_commissioner/nearby_places_loader.rb
> +    GOOGLE_MAP_API_URL = 'https://maps.googleapis.com/maps/api'.freeze
Yeah that's better

2023-03-03 08:12 UTC, panhachom commented on config/routes.rb
> +          patch :update
![Screenshot from 2023-03-03 15-07-20](https://user-images.githubusercontent.com/92453740/222666765-5c3452cc-f35e-4bba-acb1-700248c73fc2.png)

without set this it will trigger this error

2023-03-06 11:43 UTC, theachoem commented
@panhachom change commit name to this instead: https://github.com/channainfo/commissioner/issues/182

2023-03-10 01:12 UTC, merged