Close #190 variant pricing model
channainfo/commissioner pull request #209
Opened 2023-02-28 11:46 UTC by kimsrung

![image](https://user-images.githubusercontent.com/5371371/221845140-5ca34ce0-30ae-4c26-b575-d8e7b9ae6b5d.png)

2023-02-28 12:02 UTC, theachoem commented
This response will break our app core decode service bong. Would be better if it is JSON:API.

2023-02-28 15:23 UTC, channainfo requested changes

2023-02-28 15:23 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/variant_prices_controller.rb
> +            render json: collection
Let's return a serializable collection to conform with the JSON API format to make JSON API client libs operable with the server payload.

we could return: 
- a list of The variant with prices or
- a vendor with variants with prices.

Let's focus on our domain design by using the controller endpoint e.g

- Vendor -> Accommodation or Hotel
- VariantPrices -> RoomPrices

2023-02-28 15:23 UTC, channainfo commented on app/interactors/spree_cm_commissioner/variant_pricing_checker.rb
> +      variants = {}
a hash is not conform with JSON API format.

2023-03-01 04:38 UTC, channainfo requested changes

2023-03-01 04:38 UTC, channainfo commented on app/interactors/spree_cm_commissioner/variant_pricing_checker.rb
> +        (from_date..to_date).each do |day|
let's extract this to another method called **calculate_price_for_date_range(variant:, from_date:, to_date:)**

2023-03-01 04:38 UTC, channainfo commented on app/interactors/spree_cm_commissioner/variant_pricing_checker.rb
> +        rule = variant_pricing_rule.pricing_rule.date_rule
let's extract this to PriceRule#matched? method. This is our core business logic we need to have it on it own method.

2023-03-01 04:38 UTC, channainfo commented on app/interactors/spree_cm_commissioner/variant_pricing_checker.rb
> +        variant.price_by_date = prices
let's use the plural form ** price_by_date **

2023-03-01 04:38 UTC, channainfo commented on app/models/spree_cm_commissioner/variant_decorator.rb
> +      base.attribute    :price_by_date
can we just use attr_accessor instead? Let move it all the way down  right below the relationships section

2023-03-01 04:38 UTC, channainfo commented on app/models/spree_cm_commissioner/variant_decorator.rb
> +    def active_pricing_rules
let's use the relationships instead so we can eager load with e.g includes.

2023-03-01 04:40 UTC, channainfo commented
@kimsrung our very first price rules will be set at the vendor level. The price rule per room could be possible with the next step using option types.

2023-03-02 08:27 UTC, channainfo requested changes

2023-03-02 08:27 UTC, channainfo commented on app/interactors/spree_cm_commissioner/variant_pricing_checker.rb
> +      variant_pricing = variant.active_pricing_rules.find do |variant_pricing_rule|
@kimsrung I believe when you do this variant.active_pricing_rules.find, rails will trigger multiple queries to sql which is not preferable.  we might enforce rails to see from the memory 
**variant.active_pricing_rules.to_a.find**

2023-03-02 08:27 UTC, channainfo commented on app/interactors/spree_cm_commissioner/variant_pricing_checker.rb
> +      variant_pricing = variant.active_pricing_rules.find do |variant_pricing_rule|
@kimsrung Correct me if i am wrong, as we discussed, we would use the price rules defined by the vendor not the variant one.

2023-03-06 02:59 UTC, channainfo requested changes

2023-03-06 02:59 UTC, channainfo commented on app/interactors/spree_cm_commissioner/price_rule.rb
> +  class PriceRule < BaseInteractor
@kimsrung we don't need this as an interactor,  the name of this class might confuse us with the AR model. let's move this method to it the AR model instead.

2023-03-06 02:59 UTC, channainfo commented on app/interactors/spree_cm_commissioner/accommodation_price_rule.rb
> +  class AccommodationPriceRule < BaseInteractor
let's add specs for this. 
can you also rename AccommodationPriceRule to something else? this name sounds like an AR model. The -er, -or suffix should be good ( AccommodationPriceRuleInteractor / AccommodationPriceRuleCalculator, ... )

2023-03-06 02:59 UTC, channainfo commented on app/interactors/spree_cm_commissioner/accommodation_price_rule.rb
> +        pricing_rule.price_by_dates = []
let's combine the body of the loop into one single method.  It is more obvious when we change the state we use instance var otherwise let's return it.

2023-07-21 01:45 UTC, closed without merging