WIP #2112 create job when add to cart
channainfo/commissioner pull request #2113
Opened 2024-12-05 04:44 UTC by LengTech11

2024-12-09 09:25 UTC, theachoem commented
@LengTech11

Panha will take over this.

2024-12-11 03:47 UTC, channainfo requested changes

2024-12-11 03:47 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/enqueue_cart_controller.rb
> +            struct = Struct.new(:id, :status, :queued_at, :collection_reference, :document_reference)
let's move this to a class ( serializable_objects )

2024-12-11 03:47 UTC, channainfo commented on config/routes.rb
> +        resource :enqueue_cart, controller: :enqueue_cart do
resources :add_item_queues, only: [:create]

to avoid a custom action like this

```
# POST /add_item
  def add_item
  end
end
```

2024-12-11 07:20 UTC, panhachom commented on config/routes.rb
> +        resource :enqueue_cart, controller: :enqueue_cart do
```
  namespace :queue_cart do
          resources :line_items, only: [:create]
  end
  ```
 how about i contruct like this bong ? We will use create for add_item and destroy for remove item

2024-12-11 09:58 UTC, merged