Close #2117 Update line_item to line_items on anonymous line items
channainfo/commissioner pull request #2172
Opened 2024-12-19 05:55 UTC by SreyMochOrng

2024-12-24 06:57 UTC, channainfo requested changes

2024-12-24 06:57 UTC, channainfo commented on app/controllers/spree/api/v2/storefront/anonymous_line_items_controller.rb
> +          def show_anonymous_line_items
let's use the **show** method

2024-12-26 05:02 UTC, channainfo commented on config/routes.rb
> +        resources :anonymous_line_items, only: %i[show]
Let's change the path to /s ,for example, /s/L7775432?sk=jwt_token

2024-12-26 05:16 UTC, panhachom commented on config/routes.rb
> +        resources :anonymous_line_items, only: %i[show]
/s is reserved bong. eg. https://www.bookme.plus/s/hotel. /t also reserved by taxons.

How about /l (L) bong?

2024-12-26 09:30 UTC, merged