184 service calender
channainfo/commissioner pull request #230
Opened 2023-03-14 08:34 UTC by kimsrung

Request: {{apiServerUrl}}/api/v2/storefront/accommodations?province_id=583&from_date=2023-03-01&to_date=2023-03-30

Response
```
{
    "data": [
        {
            "id": "2",
            "type": "accommodation",
            "attributes": {
                "name": "Bamboo Bungalows",
                "about_us": "The car parking and the Wi-Fi are always free, so you can stay in touch and come and go as you please. Conveniently situated in the Kampot City Center part of Kampot, this property puts you close to attractions and interesting dining options. Don't leave before paying a visit to the famous Preah Monivong National Park. This 4-star property features restaurant to make your stay more indulgent and memorable.",
                "slug": "bamboo-bungalows",
                "contact_us": "https://www.agoda.com/bamboo-bungalows/hotel/kampot-kh.html [+855 883-456-789](tel:883456789)",
                "min_price": "15.0",
                "max_price": "1234.0",
                "star_rating": 4,
                "short_description": "",
                "total_inventory": 0,
                "service_availabilities": [
                    {
                        "date": "2023-03-01",
                        "available": true
                    },
                    {
                        "date": "2023-03-02",
                        "available": true
                    },
                    {
                        "date": "2023-03-03",
                        "available": true
                    },
                    {
                        "date": "2023-03-04",
                        "available": true
                    },
                    {
                        "date": "2023-03-05",
                        "available": true
                    },
                    {
                        "date": "2023-03-06",
                        "available": true
                    },
                    {
                        "date": "2023-03-07",
                        "available": true
                    },
                    {
                        "date": "2023-03-08",
                        "available": true
                    },
                    {
                        "date": "2023-03-09",
                        "available": true
                    },
                    {
                        "date": "2023-03-10",
                        "available": true
                    },
                    {
                        "date": "2023-03-11",
                        "available": true
                    },
                    {
                        "date": "2023-03-12",
                        "available": true
                    },
                    {
                        "date": "2023-03-13",
                        "available": true
                    },
                    {
                        "date": "2023-03-14",
                        "available": true
                    },
                    {
                        "date": "2023-03-15",
                        "available": true
                    },
                    {
                        "date": "2023-03-16",
                        "available": true
                    },
                    {
                        "date": "2023-03-17",
                        "available": true
                    },
                    {
                        "date": "2023-03-18",
                        "available": true
                    },
                    {
                        "date": "2023-03-19",
                        "available": true
                    },
                    {
                        "date": "2023-03-20",
                        "available": true
                    },
                    {
                        "date": "2023-03-21",
                        "available": true
                    },
                    {
                        "date": "2023-03-22",
                        "available": true
                    },
                    {
                        "date": "2023-03-23",
                        "available": true
                    },
                    {
                        "date": "2023-03-24",
                        "available": true
                    },
                    {
                        "date": "2023-03-25",
                        "available": true
                    },
                    {
                        "date": "2023-03-26",
                        "available": true
                    },
                    {
                        "date": "2023-03-27",
                        "available": true
                    },
                    {
                        "date": "2023-03-28",
                        "available": true
                    },
                    {
                        "date": "2023-03-29",
                        "available": true
                    },
                    {
                        "date": "2023-03-30",
                        "available": true
                    }
                ],
                "total_booking": 0,
                "remaining": 0
            },
            "relationships": {
                "image": {
                    "data": null
                },
                "products": {
                    "data": [
                        {
                            "id": "8",
                            "type": "product"
                        },
                        {
                            "id": "4",
                            "type": "product"
                        }
                    ]
                },
                "stock_locations": {
                    "data": [
                        {
                            "id": "3",
                            "type": "stock_location"
                        }
                    ]
                },
                "variants": {
                    "data": []
                },
                "photos": {
                    "data": [
                        {
                            "id": "7",
                            "type": "photo"
                        },
                        {
                            "id": "8",
                            "type": "photo"
                        },
                        {
                            "id": "9",
                            "type": "photo"
                        },
                        {
                            "id": "10",
                            "type": "photo"
                        },
                        {
                            "id": "11",
                            "type": "photo"
                        },
                        {
                            "id": "12",
                            "type": "photo"
                        },
                        {
                            "id": "13",
                            "type": "photo"
                        }
                    ]
                },
                "vendor_kind_option_types": {
                    "data": [
                        {
                            "id": "17",
                            "type": "option_type"
                        },
                        {
                            "id": "21",
                            "type": "option_type"
                        }
                    ]
                },
                "promoted_option_types": {
                    "data": [
                        {
                            "id": "17",
                            "type": "option_type"
                        }
                    ]
                },
                "nearby_places": {
                    "data": []
                },
                "places": {
                    "data": []
                },
                "promoted_option_values": {
                    "data": [
            [...]

2023-03-14 08:57 UTC, channainfo requested changes

2023-03-14 08:57 UTC, channainfo commented on app/interactors/spree_cm_commissioner/accommodation_search_detail.rb
> +      calendar = accommodation_service_calendars.find { |s| s.calendarable_id == vendor.id && s.day.to_date == day.to_date }
This will loop the query.  You might first eager-load the service calendars of all the vendors and then get the service calendars per vendor to avoid the n+1 query.

2023-03-14 08:57 UTC, channainfo commented on app/models/spree_cm_commissioner/vendor_decorator.rb
> +      base.attribute :service_availabilities, default: []
I think we already use  **attr_accessor** for the virtual attribute. let's add comments for each attribute we use

2023-03-14 08:57 UTC, channainfo commented on db/migrate/20230313030639_create_service_calendars.rb
> +
we miss the exception_type ( inclusion / exclusion ) https://developers.google.com/transit/gtfs/reference#calendartxt.

2023-03-15 06:12 UTC, kimsrung commented on app/interactors/spree_cm_commissioner/accommodation_search_detail.rb
> +      calendar = accommodation_service_calendars.find { |s| s.calendarable_id == vendor.id && s.day.to_date == day.to_date }
accommodation_service_calendars is an array. It wont query database as n+1 query.

2023-03-16 13:11 UTC, channainfo requested changes

2023-03-17 12:29 UTC, kimsrung commented on db/migrate/20230315023131_create_service_calendar_dates.rb
> +    create_table :cm_service_calendar_dates, if_not_exists: true do |t|
keep it for now. We will move it in the next task

2023-03-21 01:40 UTC, channainfo requested changes

2023-03-21 01:40 UTC, channainfo commented on app/interactors/spree_cm_commissioner/apply_service_availability.rb
> +                                                                         .order(created_at: :desc)
let's order by id instead much faster.

2023-03-21 01:40 UTC, channainfo commented on app/interactors/spree_cm_commissioner/apply_service_availability.rb
> +      calendarable.respond_to?(:each) ? calendarable.map(&:id).uniq : calendarable.id
let's not delegate calendarable but to create a method calendarable and make sure it handle the array

context.calendarable.class == Array ? context.calendarable : [context.calendarable]

2023-03-21 03:03 UTC, kimsrung commented on app/models/spree_cm_commissioner/service_calendar.rb
> +      return exception_calendar.inclusion? if exception_calendar.present?
currently it's correct. if it's exclusion, exception_calendar.inclusion? will return false.

2023-03-21 03:08 UTC, kimsrung commented on app/interactors/spree_cm_commissioner/apply_service_availability.rb
> +      calendarable.respond_to?(:each) ? calendarable.map(&:id).uniq : calendarable.id
we still need to check condition with context.calendarable.respond_to?(:each) because it is the ActiveRecord::Relation

2023-03-21 04:35 UTC, merged