close #288 added cron job for subscriptions
channainfo/commissioner pull request #289
Opened 2023-03-30 09:58 UTC by tykeaboyloy

2023-03-30 10:45 UTC, channainfo requested changes

2023-03-30 10:45 UTC, channainfo commented on app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
> +      load_remaindings
there is a typo

2023-03-30 10:45 UTC, channainfo commented on app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
> +      context.remaindings = SpreeCmCommissioner::Subscription.active.joins(:line_items).where(line_items: { id: last_line_items })
use the **window function** rank() in Postgres. You might not need last_line_items anymore

2023-03-30 10:45 UTC, channainfo commented on app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
> +        subscription.update(last_occurence: subscription.line_items.first.to_date)
create a new column called "version" as an int in the subscriptions table to apply the optimistic lock. 
Make sure to call SubscribedOrderCreator only if the subscription updated successfully.

2023-03-30 10:46 UTC, channainfo requested changes

2023-03-30 10:46 UTC, channainfo commented on app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
> +      context.last = Spree::LineItem.where(order: Spree::Order.select('MAX(id) AS id').group(:subscription_id)).where('to_date < ?', Time.zone.today)
remove the assignment from the context if not needed

2023-03-31 03:12 UTC, theachoem commented
```sql
WITH subscription_orders AS (
    SELECT id, number, subscription_id 
    FROM "spree_orders" 
    WHERE subscription_id IS NOT NULL
    ORDER BY subscription_id
),

partition_orders AS (
    SELECT id, subscription_id, rank() OVER (PARTITION BY subscription_id ORDER BY id DESC)
    FROM subscription_orders
),

last_orders AS (
    SELECT * FROM partition_orders 
    WHERE rank = 1
),

remain_subscriptions AS (
    SELECT * FROM cm_subscriptions AS s
        INNER JOIN last_orders AS o ON o.subscription_id = s.id
        INNER JOIN spree_line_items AS l ON l.id = o.id
    WHERE l.to_date < Now()
)

SELECT * FROM remain_subscriptions
```

2023-04-02 07:15 UTC, theachoem approved these changes

2023-04-02 07:15 UTC, theachoem commented on app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
> +      from_date = subscription.last_occurence || subscription.start_date
from_date = (subscription.last_occurence + months_count) || subscription.start_date

2023-04-02 07:16 UTC, theachoem requested changes

2023-04-02 07:16 UTC, theachoem commented on app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
> +      from_date = subscription.last_occurence || subscription.start_date
from_date = (subscription.last_occurence + months_count) || subscription.start_date

2023-04-02 15:49 UTC, tykeaboyloy commented on app/interactors/spree_cm_commissioner/subscribed_order_creator.rb
> +      from_date = subscription.last_occurence || subscription.start_date
subscription.last_occurence + months_count = to_date

2023-04-03 12:27 UTC, channainfo commented on app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
> +      remaining_subscriptions.each do |subscription|
use find_each instead of each.
```
remaining_subscriptions.find_each
```

2023-04-03 12:30 UTC, channainfo commented on app/interactors/spree_cm_commissioner/subscriptions_order_cron_executor.rb
> +      remaining_subscriptions.each do |subscription|
@tykeaboyloy resolve conflict

2023-04-04 06:23 UTC, channainfo requested changes

2023-04-04 06:23 UTC, channainfo commented on spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
> +      instance = described_class.new(current: '2021-03-01')
Inconsistent data type. Here https://github.com/channainfo/commissioner/pull/289/files#diff-22dc2f1a45be899bfd820bc62c9ed3b5122a15279e0f0258ef701a24ea7d5f15R30 we use Date object but in the test we use string. Make sure the values are the same type. 
Let's use a Date object instead of a string object.

2023-04-04 06:25 UTC, channainfo commented on spec/interactors/spree_cm_commissioner/subscriptions_order_cron_executor_spec.rb
> +      instance = described_class.new(current: '2021-03-01')
@tykeaboyloy add the https://github.com/channainfo/commissioner/pull/289#issuecomment-1491230292 to docs/sql/subscriptions/remaining_subscriptions.sql

2023-04-04 16:16 UTC, tykeaboyloy commented
> ```sql
> WITH subscription_orders AS (
>     SELECT id, number, subscription_id 
>     FROM "spree_orders" 
>     WHERE subscription_id IS NOT NULL
>     ORDER BY subscription_id
> ),
> 
> partition_orders AS (
>     SELECT id, subscription_id, rank() OVER (PARTITION BY subscription_id ORDER BY id DESC)
>     FROM subscription_orders
> ),
> 
> last_orders AS (
>     SELECT * FROM partition_orders 
>     WHERE rank = 1
> ),
> 
> remain_subscriptions AS (
>     SELECT * FROM cm_subscriptions AS s
>         INNER JOIN last_orders AS o ON o.subscription_id = s.id
>         INNER JOIN spree_line_items AS l ON l.id = o.id
>     WHERE l.to_date < Now()
> )
> 
> SELECT * FROM remain_subscriptions
> ```

renewed verson
```sql
WITH
partition_orders AS (
	SELECT id,number, subscription_id, rank() OVER (PARTITION BY subscription_id ORDER BY id DESC) FROM spree_orders
	WHERE subscription_id IS NOT NULL
),

last_orders as (
SELECT  id, number,subscription_id,rank FROM partition_orders where rank = 1
),

remain_subscriptions AS (
    SELECT * FROM cm_subscriptions AS s
        INNER JOIN last_orders AS o ON o.subscription_id = s.id
        INNER JOIN spree_line_items AS l ON l.order_id = o.id
    WHERE l.to_date < Now()
)

SELECT * from remain_subscriptions
```

2023-04-05 01:14 UTC, merged