close #405 add penalty to payment
channainfo/commissioner pull request #406
Opened 2023-06-09 09:33 UTC by tykeaboyloy

<img width="1440" alt="image" src="https://github.com/channainfo/commissioner/assets/87005466/c107ff5d-a164-423a-b4f0-9b6e1888f446">
<img width="1440" alt="image" src="https://github.com/channainfo/commissioner/assets/87005466/f004796d-2b53-46c5-80f3-debbc7069b36">
<img width="1440" alt="image" src="https://github.com/channainfo/commissioner/assets/87005466/34141dfc-b31b-4d32-b92b-21472c685807">
<img width="1201" alt="image" src="https://github.com/channainfo/commissioner/assets/87005466/ee6b1998-f78c-491e-a10b-9d20b02a7f6d">

2023-06-09 10:01 UTC, theachoem requested changes

2023-06-09 10:43 UTC, channainfo requested changes

2023-06-09 10:43 UTC, channainfo commented on app/overrides/spree/admin/shared/_order_summary/penalty.html.erb.deface
> +
use alignment properly.

2023-06-12 02:58 UTC, theachoem commented
@tykeaboyloy should update screenshots

2023-06-12 03:04 UTC, theachoem commented on app/views/spree/billing/adjustments/new.html.erb
Should add some space:
```rb
<%= render partial: 'spree/billing/shared/order_tabs', locals: { current: :adjustment } %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @adjustment } %>

<%= form_for @adjustment, url: billing_order_adjustments_path do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links'%>
  </fieldset>
<% end %>
```

2023-06-12 03:06 UTC, theachoem commented on app/views/spree/billing/adjustments/index.html.erb
> +<%= render partial: 'spree/billing/shared/order_tabs', locals: { current: :adjustment } %>
Add some space between blocks.
```rb
<%= render partial: 'spree/billing/shared/order_tabs', locals: { current: :adjustment } %>

<% content_for :page_actions do %>
  <%= button_link_to(Spree.t(:new_adjustment), new_billing_order_adjustment_path(@order), class: "btn-success", icon: 'add.svg') if can? :create, Spree::Adjustment %>
<% end %>

<% if @adjustments.present? %>
  <div class="card mb-3">
    <%= render partial: 'adjustments_table'%>
  </div>
<% else %>
  <div class="text-center m-5">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Adjustment)) %>
  </div>
<% end %>
<% if @order.can_add_coupon? %>
  <div class="card bg-light mb-3" data-hook="adjustments_new_coupon_code">
    <div class="card-body">
      <div class="form-group">
        <%= text_field_tag "coupon_code", "", placeholder: Spree.t(:coupon_code), class: "form-control" %>
      </div>
      <%= button Spree.t(:add_coupon_code), 'add.svg', 'submit', id: "add_coupon_code" %>
    </div>
  </div>
<% end %>

<script>
  var order_number = '<%= @order.number %>';
  var order_id = '<%= @order.id %>';
</script>

<%= render partial: 'spree/admin/shared/order_summary' %>
```

2023-06-19 01:50 UTC, channainfo requested changes

2023-06-19 01:50 UTC, channainfo commented on app/controllers/spree/billing/payments_controller.rb
> +        @penalty_length = (Time.zone.now - @order.line_items.first.due_date).to_i / 1.day
make sure we have the same unit. add a unit name in the var e.g.:  @penalty_in_day. Move this to a service and write a spec for this.

2023-06-19 01:50 UTC, channainfo commented on app/controllers/spree/billing/adjustments_controller.rb
> +        @adjustments = @order.all_adjustments.eligible.order(created_at: :asc)
Add a pagination.

2023-06-19 01:50 UTC, channainfo commented on app/views/spree/billing/shared/_invoice.html.erb
> +            <%  @order.adjustments.map do |adjustment|  %>
use **each** instead of **map**

2023-06-20 10:23 UTC, channainfo requested changes

2023-06-20 10:23 UTC, channainfo commented on spec/services/spree_cm_commissioner/penalty_calculator_spec.rb
> +      current_time = Time.zone.now
mock current time to a certain date ej: 2023-06-15

then expect the date to be a certain value for example in this case 35 days.
```
expected_penalty_in_days = 35
expect(calculated_penalty).to eq(expected_penalty_in_days)

```
and remove this ```penalty_in_days = ((current_time - due_date).to_i / 1.day).to_i``` because it is an object under test.

2023-06-20 10:23 UTC, channainfo commented on app/services/spree_cm_commissioner/penalty_calculator.rb
> +      ((Time.zone.now - order.line_items.first.due_date).to_i / 1.day).to_i
Add a test for this. To make it easy you can just pass due_date instead of the whole order in.

```
def self.calculate_penalty_in_days(due_date)
  ((Time.zone.now - due_date).to_i / 1.day).to_f..ceil
end
```
coz 1.2 days become 2days.

2023-06-23 05:07 UTC, merged