close #19 product amentity with option value
channainfo/commissioner pull request #46
Opened 2022-12-09 04:56 UTC by theachoem

- Add validation
- Add spec to prove it work

2022-12-14 02:52 UTC, channainfo requested changes

2022-12-14 02:52 UTC, channainfo commented on app/models/spree/variant_decorator.rb
> +        if is_master?
combine  if is_master? &&  attr_type != "amenity"

2022-12-14 02:52 UTC, channainfo commented on app/models/spree/variant_decorator.rb
> +        if is_master?
non-master: true

2022-12-15 03:18 UTC, closed without merging

2022-12-15 04:01 UTC, theachoem commented
As it is a BIG scope, let track PRs in issue https://github.com/channainfo/commissioner/issues/19 instead: