close #520 added a qrcode field to vendor
channainfo/commissioner pull request #521
Opened 2023-08-22 09:54 UTC by tykeaboyloy

-add vendor edit section to billing
<img width="1439" alt="image" src="https://github.com/channainfo/commissioner/assets/87005466/7a43f07a-c706-4741-b28b-3a35c559a0f6">

-add qrcode field to vendor asset
-use the qrcode in invoice for payment
<img width="1151" alt="image" src="https://github.com/channainfo/commissioner/assets/87005466/4add964a-8357-4740-a6dd-a3329fdd56ca">

2023-08-22 10:20 UTC, channainfo requested changes

2023-08-22 10:20 UTC, channainfo commented on app/models/spree_cm_commissioner/vendor_qrcode.rb
> +  class VendorQrcode < Asset
QR code is not a form of representing URL in a machine-readable way. You can use ruby or js lib to generate the QRCode by taking an URL as input. No need to store it as an asset.

2023-08-23 07:49 UTC, tykeaboyloy commented on app/models/spree_cm_commissioner/vendor_qrcode.rb
> +  class VendorQrcode < Asset
Bong if we store the url and use it to generate the QRCode ourselves, the generated QRCode can only be scanned through third party scanner, but cannot be scanned using bank app (aba, acleda).

2023-08-28 02:45 UTC, channainfo commented
@tykeaboyloy let's rename it to payment_qrcode to be not confused with a normal qr.

2023-09-11 13:29 UTC, merged