Close #655 enhance vendor query response for JsonLD
channainfo/commissioner pull request #656
Opened 2023-10-04 05:37 UTC by kimsrung

2023-10-04 06:52 UTC, channainfo requested changes

2023-10-04 06:52 UTC, channainfo commented on app/models/spree_cm_commissioner/vendor_decorator.rb
> +    def full_address
This method is complicated and resource-consuming and it is easy to mislead for example, if we call this method with a list of vendors, it will cause a crazy query and be very resource-intensive.

If this info is important, let's just create a new field in the vendor and read from it instead.

2023-10-05 01:15 UTC, kimsrung commented on app/serializers/spree/v2/storefront/vendor_serializer_decorator.rb
> +            image = vendor.image || vendor.logo
yes, we need that image for JSON-LD only. Sometimes, logo is blank. That's y I use image or logo.

2023-10-05 01:38 UTC, channainfo requested changes

2023-10-05 01:38 UTC, channainfo commented on app/serializers/spree/v2/storefront/vendor_serializer_decorator.rb
> +            image = vendor.image || vendor.logo
If you need a specific logic for JSON-LD, create a new serializer under jsonld instead. Take into account that adding a new model to a serializer will put a huge burden on others who use the same serializer.

2023-10-05 04:37 UTC, channainfo requested changes

2023-10-05 04:37 UTC, channainfo commented on app/controllers/spree/api/json_ld/vendors_controller.rb
> +      end
we need to make sure that the collection is eager load the image includes(:image)

2023-10-05 04:37 UTC, channainfo commented on app/serializers/spree_cm_commissioner/json_ld/vendor_serializer.rb
> +
has_one :image

2023-10-05 04:37 UTC, channainfo commented on app/serializers/spree_cm_commissioner/json_ld/vendor_serializer.rb
> +      attributes :image_url
remove this, we use includes(:image) instead.

2023-10-05 09:25 UTC, merged