close #830 edit line item fields backend
channainfo/commissioner pull request #860
Opened 2023-11-29 04:42 UTC by Thornsopanha

# Edit Screen UI
<img width="720" alt="Screenshot 2023-11-29 at 10 57 55 AM" src="https://github.com/channainfo/commissioner/assets/87221718/69fd0f4b-e0c7-4c8e-8a16-7ca1cb1925d2">

2023-11-29 04:54 UTC, theachoem commented on app/controllers/spree/admin/line_items_controller.rb
> +
```
def location_after_save
  admin_cart_orders_path(@order)
end
```

2023-11-30 04:03 UTC, theachoem approved these changes
LGTM

2023-11-30 04:07 UTC, theachoem commented on config/routes.rb
> +      resources :line_items
resources :line_items, only: %i[update edit]

2023-11-30 04:10 UTC, theachoem commented on app/views/spree/admin/line_items/edit.html.erb
> +<% end %>
```rb
<%= render partial: 'spree/admin/shared/order_tabs', locals: { current: :cart } %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @line_item } %>
<%= form_with model: @line_item, url: { action: 'update' } do |f| %>
  <%= render partial: 'form', locals: { f: f } %>
  <div data-hook="admin_line_item_edit_form_button">
    <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: spree.admin_orders_path } %>
  </div>
<% end %>
```

2023-11-30 04:16 UTC, theachoem approved these changes
LGTM

2023-11-30 04:57 UTC, channainfo requested changes

2023-11-30 04:57 UTC, channainfo commented on app/controllers/spree/admin/line_items_controller.rb
> +        @line_item = LineItem.find(params[:id])
let's find the line item from the order to make sure that the route is nested under the order resources and the line_item work only if the order is valid:

```
@order = Spree::Order.find(params[:order_id])
@line_item = @order.line_items.find(params[:id])
```

2023-11-30 11:05 UTC, merged