close #865 update user confirmation code
channainfo/commissioner pull request #886
Opened 2023-12-09 03:41 UTC by vaneath

2023-12-10 17:21 UTC, theachoem commented on app/interactors/spree_cm_commissioner/user_pin_code_authenticator.rb
> +      Spree::User.where(id: context.user.id).update(confirmed_at: Time.zone.now)
In devise, we can just use skip_confirmation! Call it before creating.

`context.user.skip_confirmation!`

Learn more how devise confirmation work:
https://github.com/heartcombo/devise/blob/main/lib/devise/models/confirmable.rb

2023-12-12 04:22 UTC, vaneath commented on app/interactors/spree_cm_commissioner/user_pin_code_authenticator.rb
> +      Spree::User.where(id: context.user.id).update(confirmed_at: Time.zone.now)
Solve it with manually set confirmed_at with Time.zone.now

2023-12-13 03:16 UTC, channainfo requested changes

2023-12-13 03:16 UTC, channainfo commented on app/interactors/spree_cm_commissioner/user_pin_code_authenticator.rb
> +      user[:confirmed_at] = Time.zone.now
use **user. confirmed_at** instead. Add a spec to make sure this field is assigned correctly

2023-12-13 12:59 UTC, merged