Close #912 Transit Add DataType to taxon
channainfo/commissioner pull request #913
Opened 2023-12-19 11:18 UTC by chheng-dev

2023-12-19 11:22 UTC, chheng-dev commented
#### Create New Taxon 
![image](https://github.com/channainfo/commissioner/assets/95673107/d2dce3c5-203a-44c4-a07e-3209bf24b814)

`` When selecting a location for a branch and stop, the disabled access should be considered 
``
![image](https://github.com/channainfo/commissioner/assets/95673107/12bcca46-6318-4126-b58b-fe8ce42fc8e4)

2023-12-22 02:20 UTC, channainfo requested changes

2023-12-22 02:20 UTC, channainfo commented on db/migrate/20231219111615_add_data_type_to_spree_taxon.rb
> +    add_column :spree_taxons, :data_type, :integer
add the option default: 0

2023-12-22 02:20 UTC, channainfo commented on app/views/spree/transit/taxons/edit.html.erb
> +<%= form_with model: @object, url: { action: 'update'}, id: "checkboxForm" do |f| %>
the id and class with dash: "checkbox-form"

2024-01-15 04:38 UTC, merged