wip #922 add kyc field to spree product
channainfo/commissioner pull request #923
Opened 2023-12-21 04:29 UTC by panhachom

https://github.com/channainfo/commissioner/assets/92453740/728830b6-03f0-4e5a-9ec7-9380f0cad73e

2023-12-21 08:28 UTC, channainfo requested changes

2023-12-21 08:28 UTC, channainfo commented on db/migrate/20231220071350_add_kyc_field_to_spree_products.rb
> +    add_column :spree_products, :kyc_field, :integer, if_not_exists: true
add a default value to 0. why don't just use the existing kyc field by changing the column from boolean to integer

2023-12-21 08:28 UTC, channainfo commented on app/models/concerns/spree_cm_commissioner/kyc_field_bitwise.rb
> +      kyc_field.present?
let's use need_kyc? instead. I think we have many need_  in our code base.
present? for zero is true so make sure it is present and not zero. Probably
!kyc_field.zero?

2023-12-21 09:20 UTC, panhachom commented on app/models/concerns/spree_cm_commissioner/kyc_field_bitwise.rb
> +      kyc_field.present?
done bong

2023-12-21 10:17 UTC, channainfo commented
@panhachom failed!!!

2023-12-21 11:55 UTC, panhachom commented
> @panhachom failed!!!
resolved bong

2023-12-22 02:41 UTC, channainfo requested changes

2023-12-22 02:41 UTC, channainfo commented on app/interactors/spree_cm_commissioner/kyc_calculator.rb
> +    def call
This method has no interactions and failure status so simple so let's just put in a **module** and include it instead. Let's add a spec for this as well.

2023-12-22 02:41 UTC, channainfo commented on app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
> +
Probably merge the kyc calculator with this one and call it kycable.rb

2023-12-22 02:41 UTC, channainfo commented on config/routes.rb
> +      resources :kyc, only: %i[index update] do
here KYC is not a resource/resources, I think it would be better to call it get :edit_kyc and put :update_kyc under the products controller

2023-12-22 09:08 UTC, panhachom commented on app/models/concerns/spree_cm_commissioner/kyc_bitwise.rb
> +
Since we have set kyc default value to 0 we don't need this method anymore

2023-12-26 10:30 UTC, merged