close #980 added route_type field to vehicle
channainfo/commissioner pull request #981
Opened 2024-01-08 10:00 UTC by tykeaboyloy

<img width="1207" alt="image" src="https://github.com/channainfo/commissioner/assets/87005466/9710cd9e-b1c2-4324-a42e-25075e86ad35">

2024-01-08 13:26 UTC, channainfo requested changes

2024-01-08 13:26 UTC, channainfo commented on app/models/spree_cm_commissioner/vehicle.rb
> +      selected_vehicle_type = VehicleType.find_by(id: vehicle_type_id)
it can be as simple as
```
self.route_type = vehicle_type.route_type
```
vehicle must have a vehicle_type. Use this in the before_save instead.

2024-01-09 03:33 UTC, tykeaboyloy commented on app/models/spree_cm_commissioner/vehicle.rb
> +      selected_vehicle_type = VehicleType.find_by(id: vehicle_type_id)
@channainfo  done bong

2024-01-11 02:27 UTC, channainfo commented
@tykeaboyloy resolve conflict

2024-01-11 03:12 UTC, tykeaboyloy commented
> @tykeaboyloy resolve conflict

2024-01-15 04:36 UTC, merged